/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-09-04 06:59:14
 * Facility Type: Radiology
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Radiology = {
    "ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure?",
            "Is the director a medically trained person?",
            "Does the facility comply with regulatory requirements for Business registration?",
            "Does the facility comply with regulatory requirements for Work permits?",
            "Does the facility comply with regulatory requirements for Lease agreement?",
            "Does the facility comply with regulatory requirements for Trading license?",
            "Does the facility comply with regulatory requirements for Occupancy certificate?",
            "Does the facility comply with regulatory requirements for Patient charter in English & Setswana?",
            "Does the facility comply with regulatory requirements for Copies of relevant statutory instruments e.g. Public Health Act 2013, Botswana Health Professions Act,2001?",
            "Does the facility comply with regulatory requirements for Is there an indemnity insurance??",
            "Does the facility comply with regulatory requirements for Have personnel been cleared by police??",
            "Does the facility comply with regulatory requirements for contracts for staff?",
            "Does the facility comply with regulatory requirements for letter of permission to set up/operate?",
            "Does the facility comply with regulatory requirements for waste collection carrier licence?",
            "Does the facility comply with regulatory requirements for confidentiality clause?",
            "Does the facility comply with regulatory requirements for tax clearance certificate?",
            "Does the facility comply with regulatory requirements for Practitioner?s licence?",
            "Does the facility comply with regulatory requirements for Fire clearance?",
            "Does the facility comply with regulatory requirements for work permits?",
            "Does the facility comply with regulatory requirements for residence permit?",
            "Does the Facility have policies and procedures for referral systems?",
            "Does the Facility have policies and procedures for assessment of patients?",
            "Does the Facility have policies and procedures for treatment protocols?",
            "Does the Facility have policies and procedures for testing and treatment techniques?",
            "Does the Facility have policies and procedures for high risk patients and procedures, and?",
            "Does the Facility have policies and procedures for the confidentiality of patient information?",
            "Does the Facility have policies and procedures for incident reporting?",
            "Does the Facility have policies and procedures for Induction and orientation?",
            "Does the Facility have policies and procedures for patient consent?",
            "Does the Facility have policies and procedures for Linen management?",
            "Does the Facility have policies and procedures for Equipment maintenance plan/program?",
            "Does the Facility have policies and procedures for Testing and commissioning certificates?",
            "Does the Facility have policies and procedures for Infection prevention and control?",
            "Does the Facility have policies and procedures for Management of patient records and retention times?",
            "Does the Facility have policies and procedures for Management of information ?",
            "Does the Facility have policies and procedures for Risk management ?",
            "Does the Facility have policies and procedures for Management of supplies?",
            "Does the Facility have policies and procedures for Patient observation?",
            "Does the Facility have policies and procedures for Management of medication?",
            "Does the Facility have policies and procedures for Post exposure prophylaxis?",
            "Does the Facility have policies and procedures for Complaints procedure?",
            "Does the Facility have policies and procedures for Outreach services?",
            "Does the Facility have policies and procedures for Waste management?",
        ]
    },
    "SERVICES PROVIDED": {
        "showOnly": [
            "Clinic provide Gynaecology services?",
            "Clinic provide Fertility?",
            "Clinic provide Sexual reproductive health?",
            "Clinic provide Antenatal care?",
            "Clinic provide Post-natal care?",
            "Clinic provide Post-abortal care?",
            "Clinic provide Lab-Specialist services (specify)?",
            "Clinic provide Lab-Laboratory services(specify)?",
            "Clinic provide Lab-Specimen collection (specify)?",
            "Clinic provide Eye- Vision services?",
            "Clinic provide Eye -Medical eye care?",
            "Clinic provide Eye- Surgical eye care?",
            "Clinic provide Eye- Diagnosis & treatment of eye conditions?",
            "Clinic provide Eye- Plastic surgery?",
            "Clinic provide General practice?",
            "Clinic provide Specialist services?",
            "Clinic provide Home visits?",
            "Clinic provide Others ?",
            "Clinic provide General consultations?",
            "Clinic provide Hearing & balance services?",
            "Clinic provide Voice, speech & swallowing?",
            "Clinic provide Allergy, sinuses & sleep disorders?",
            "Clinic provide Medical examinations ?",
            "Clinic provide Dental surgery?",
            "Clinic provide Cosmetic dentistry (braces and implants)?",
            "Clinic provide Community health services (Preventive)?",
            "Clinic provide Dental whitening and teeth cleaning?",
            "Clinic provide Fillings and dentures ?",
            "Clinic provide Root canal treatment?",
            "Clinic provide Crowns and bridges?",
            "Clinic provide Addiction treatment (Alcohol and drug addiction, Gambling addiction, Sex addiction, Mood addiction, Gaming addiction)?",
            "Clinic provide Mental health/ dual diagnosis treatment?",
            "Clinic provide Chronic pain management?",
            "Clinic provide Psychometric assessment (For the disorders mentioned above and others)?",
            "What are the hours of operation?",
            "Is there a services board within the facility?",
            "What is number of patients seen per month?",
            "Any outreach services?",
            "Agreement letter with a doctor where services will be offered from?",
            "Is there provision of emergency contact numbers?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff?",
            "What is the current number of staff?",
            "How many will be Gynaecologists ?",
            "How many will be Medical Doctors?",
            "How many will be Nurses?",
            "How many will be Pharmacists?",
            "How many will be Administrative staff?",
            "How many will be Support staff?",
            "How many will be Other professionals (specify)?",
            "How many will be Specialist doctors?",
            "How many will be Ophthalmologists?",
            "How many will be Opticians?",
            "How many will be Optometrists?",
            "How many will be Physiotherapists?",
            "How many will be Physiotherapy assistants?",
            "How many will be Dentist?",
            "How many will be Dental therapist?",
            "How many will be Dental assistant?",
            "How many will be Dental technologist?",
            "How many will be ENT specialist?",
            "How many will be Psychologist?",
            "How many will be Social workers?",
            "How many will be Kitchen staff?",
            "How many will be Pharmacy technicians?",
            "How many will be Laboratory scientists?",
            "How many will be Laboratory technicians?",
            "How many will be Radiographers?",
            "How many will be Radiologists?",
            "How many will be Sonographers?",
            "How many will be Radiology technicians ?",
            "Are professionals registered with the relevant Councils?",
            "Did personnel files have Signed job effectiveness description?",
            "Did personnel files have Education credentials?",
            "Did personnel files have A signed confidentiality clause?",
            "Did personnel files have Evidence of orientation and induction?",
            "Did personnel files have Evidence of continued education?",
            "Did personnel files have Signed contracts or offer letters?",
            "Did personnel files have Medical examination certificates?",
        ]
    },
    "ENVIRONMENT": {
        "showOnly": [
            "Does the facility have wheelchair accessibility?",
            "Inspection_fac: Is it fenced, secure and easily accessible?",
            "Is there adequate space for parking?",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there adequate lighting?",
            "Is air conditioning available?",
            "Is there enough ventilation?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs?",
            "Is there parking space designated for people living with disability?",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity and water?",
        ]
    },
    "RECEPTION/WAITING AREA INSPECTION": {
        "showOnly": [
            "Does reception area have adequate space?",
            "Is the telephone/ cell phone available?",
            "Is a reception desk with chair available?",
            "Is it manned at all times?",
            "Is there an organized patient registration, screening and booking system?",
            "Are there adequate patient benches / chairs in the waiting area?",
            "Is there a computer?",
        ]
    },
    "SCREENING ROOM INSPECTION": {
        "showOnly": [
            "Does the screening room have adequate space?",
            "Does the screening room have wheelchair accessibility?",
            "Is screening room equipped with chairs and table?",
            "Is screening room equipped with sphygmomanometer?",
            "Is screening room equipped with thermometer?",
            "Is screening room equipped with glucometer and strips?",
            "Is screening room equipped with alcohol Swabs?",
            "Is screening room equipped with weighing scale (both adult and paediatric)?",
            "Is screening room equipped with height measuring device?",
            "Is screening room equipped with non sterile gloves?",
            "Is screening room equipped with waste bins with lids for clinical waste?",
            "Is screening room equipped with waste bin with lids for domestic waste?",
            "Is screening room equipped with sharps container?",
            "Is screening room equipped with hand wash facilities?",
            "Is screening room equipped with appropriate hand drying facilities?",
        ]
    },
    "CONSULTATION ROOM INSPECTION": {
        "showOnly": [
            "Does the consultation room have adequate space?",
            "Does the consultation room have wheelchair accessibility?",
            "Does the consultation room have a diagnostic set?",
        ]
    },

};

export default Radiology;
