/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2026-01-06 10:04:21
 * Facility Type: Obstetrics & Gynaecology
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const ObstetricsandGynaecology = {
    "SECTION A-ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?",
            "Business registration",
            "ta clearance certificate",
            "Valid private pactice license",
            "Work permits",
            "Residence permit",
            "Lease agreement",
            "Occupancy certificate",
            "Permission to establish/set up",
            "Patient charter in English & Setswana",
            "Is there an indemnity insurance?",
            "Contracts for staff",
            "Police Clearance",
            "Waste collection carrier licence",
            "Confidentiality clause",
            "Proof of change of land use",
            "Practitioners licence",
            "Fire clearance",
            "Patient referral",
            "Assessment of patients",
            "Management of high risk patients",
            "The confidentiality of patient information",
            "Incident reporting",
            "Induction and orientation",
            "Patient consent",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "Infection prevention and control",
            "Management of patient records",
            "Record retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post eposure prophylais",
            "Complaints procedure",
            "Disaster preparedness",
            "Waste management",
            "Others",
            "Treatment protocols/ guidelines",
            "Testing and treatment techniques",
            "Copies of relevant statutory instruments",
        ]
    },
    "SERVICES PROVIDED": {
        "showOnly": [
            "General services; Specify",
            "Specialist services; Specify",
            "Other services (Specify); .....",
            "Are services provided displayed?",
            "Are hours of operation displayed?",
            "State hours of operation",
            "Are emergency contact numbers displayed?",
            "What is number of patients seen/ Samples received per month",
            "Any outreach services? If yes state them.",
            "Is there permission to offer the outreach services",
            "Agreement letter with a practitioner where outreach services will be offered from",
            "Is there provision of emergency outreach services?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff",
            "What is the current number of staff; --",
            "General Health Professionals (Specify)",
            "Specialists (Specify)",
            "Other (Specify)",
            "Administrative Staff (Specify)",
            "Support staff (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentiality clause",
            "Evidence of orientation and induction",
            "Signed contracts or offer letters",
            "Medical eamination certificates",
            "Evidence of Continous Professional Development",
            "Does the facility have wheelchair accessibility?",
            "Is it fenced, secure and easily accessible",
            "Is there space for parking? Specify",
            "Is there parking space designated for people living with disability? Specify",
            "Does the facility have space for services provided? Specify",
            "Is there provision for ambulance parking",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there lighting in all service areas?",
            "Is air conditioning available?",
            "Is there ventilation in all service area?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity?",
            "Is there backup system for water?",
            "Where there are ramps, are there safety features?",
            "Does reception area have adequate space? Elaborate.",
            "Is the telephone/ cell phone available?",
            "Is a reception desk and chair available",
            "Is it manned at all times?",
            "Is there an organized patient registration, screening and booking system",
            "Are there adequate patient benches / chairs in the waiting area? Elaborate.",
            "Is there a waste bin?",
            "Is there a computer/ desktop?",
            "Is there patient charter available in Setswana and English?",
            "Is there available drinking water source?",
            "Are educational materials available for clients",
            "Does the screening room have adequate space? Elaborate.",
            "Does the screening room have wheelchair accessibility?",
            "At least 3 chairs and table",
            "Sphygmomanometer",
            "Thermometer",
            "Glucometer and strips",
            "Alcohol Swabs",
            "Weighing scale (both adult and paediatric)",
            "Height measuring device",
            "Non sterile gloves",
            "Clinical waste bin with lid",
            "Domestic waste bin with lid",
            "Sharps container",
            "Hand wash facilities",
            "Appropriate hand drying facilities",
            "Appropriate hand wash soap",
            "Does the consultation room have adequate space?",
            "Does the consultation room have wheelchair accessibility",
            "At least 3 Chairs and a table",
            "Alcohol swabs",
            "Appropriate hand drying facilities",
            "Appropriate soap dispenser",
            "Autoclave",
            "Cabinet/Storage space",
            "clinical waste bin with lid",
            "Cotton wool/ wipes",
            "Curette",
            "Diagnostic set*",
            "Disposable cups",
            "Disposable gloves",
            "Domestic waste bin with lid",
            "Drip stand",
            "Endoscope and endoscopic light",
            "Eamination/ treatment couch with tiltable headrest behind a curtain / screen",
            "Is the eamination/ treatment couch covered with linen?",
            "Eamination gynaecological bed/couch with strirups, covered with linen",
            "Eamination lamp*",
            "Fetoscope/ doppler",
            "Foetal monitor",
            "Forceps",
            "Glucometer* and strips",
            "Hand washing basin with running hot and cold water",
            "Hand washing soap",
            "hand drying facilities",
            "Head light / head mirror",
            "Height measuring device",
            "HIV testing kit",
            "Laryngoscope set",
            "Lubricating jell or solution",
            "Needle holders",
            "Non sterile gloves",
            "Otoscope set",
            "Pap smear test kit (brush, fiator, frosted microscope glass slides)",
            "Pen torch*",
            "Reference material",
            "Sanitary pads",
            "Sharps container",
            "Sphygmomanometer*",
            "Step to ease access to couch",
            "Sterile gloves",
            "Storage space for consumables",
            "Suction apparatus",
            "Tape measure",
            "Thermometer*",
            "Tongue depressors",
            "Ultra sound jelly",
            "Ultra sound machine*",
            "Vaginal speculae (different sizes)",
            "Weighing scale (both adult and paediatric)*",
            "#NAME?",
            "Emergency trolley with checklist",
            "Does the Emergency trolley have atleast the following as per the facility level; emergency drugs, Defibrilator/ Automated Eternal Difibrilator (AED), laryngoscope set, endotracheal tubes, ambu bags, syringes, needles, cannulas, alcohol swab, drugs, IV fluids, oygen cylinder and masks of different sizes, etc",
            "Does the procedure room have adequate space?",
            "Is the room wheelchair accessible",
            "Alcohol swabs",
            "Antiseptic ointments, creams, solutions etc.",
            "Appropriate hand drying facilities",
            "Autoclave / sterilizer",
            "Bandages and plasters",
            "Chairs",
            "Clinical waste bins with lid",
            "Cupboards with suitably surfaced bench tops",
            "Curette",
            "Dilatation and curettage set",
            "Disinfectants or antiseptic solutions",
            "Domestic waste bin with lid",
            "Drip stand",
            "Eamination couch with tiltable headrest, covered with linen",
            "Step to ease access to couch",
            "Eamination lamp*",
            "Glucometer* and strips",
            "Gynaecological  couch with stirups",
            "Hand wash facilities",
            "Handwash soap",
            "Is the couch behind a curtain or located within a screened off alcove to provide privacy",
            "Lockable refrigerator for thermolabile medications with temperature monitoring device",
            "Lubricating jell or solution",
            "Nebulizing machine and solutions",
            "Needles (different sizes)",
            "Non sterile gloves",
            "Normal saline",
            "Pap smear set",
            "Pregnancy test kit",
            "Sanitary pads",
            "Sharps container",
            "Sphygmomanometer*(both adult and paediatric)*",
            "Stainless steel sink",
            "Sterile dressing packs (sponge forceps, toothed and non-toothed forceps, straight artery forceps, 2 galley pots, sterile gauge and cotton wool swabs, kidney dish, scalpel)",
            "Sterile gloves",
            "Sterile suture pack (gallipots, needle holder, scalpel, pair of stich scissors, tooth forceps)",
            "Sutures",
            "Tongue depressors",
            "Urinary catheters (different sizes)",
            "Vaginal speculae (different sizes)",
        ]
    },
    "SLUICE ROOM": {
        "showOnly": [
            "Does the room have adequate space? Elaborate.",
            "Does the room have ventilation? Elaborate",
            "Does the room have wheelchair accessibility?",
            "Canvas bag trolley with cover",
            "Canvas bag trolley with cover for non soiled linen",
            "Canvas bag trolley with cover for soiled linen",
            "Clinical waste bins with lid",
            "Disinfectants",
            "Domestic waste bins with lid",
            "Heavy duty gloves",
            "Non sterile gloves",
            "Stainless steel sink with running water",
            "Stainless steel waste discarding sink or sluice machine",
        ]
    },
    "BLEEDING ROOM": {
        "showOnly": [
            "Does the bleeding room have adequate space? Elaborate.",
            "Does the room have wheelchair accessibility?",
            "At least      2 chairs",
            "Needles and syringes (different sizes)",
            "Vacutainers of different colours",
            "Tourniquet",
            "Plaster",
            "Cotton swab",
            "Disinfectant",
            "Sharps container",
            "Clinical waste  bin with lid",
            "Domestic waste bin with lid",
            "Hand wash basin with running hot and cold water",
            "Hand wash soap",
            "Appropriate hand drying facilities",
            "Disposable gloves",
            "Cooler bo",
            "Ice packs",
            "Specimen racks",
        ]
    },
    "TOILET FACILITIES": {
        "showOnly": [
            "Is there a minimum of two toilets available (for male and",
            "Female patients)?",
            "Are they labelled male and female?",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does the Facility have a policy on waste management?",
            "Does the Facility have SOPs on waste management?",
            "Does the Facility have a waste disposal system? Specify:--",
            ". Domestic Waste",
            ".Clinical Waste",
            ".Does the Facility have a policy and procedures on safety?",
            ".Is there a policy and procedure on accidental eposure to HIV?",
            "Does the Facility have fire protection equipment?--",
            ".Fire etinguishers",
            ".Emergency eits",
            "Additional:--",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the Facility have a written program for maintaining fire protection equipment ?",
            "Does the Facility have adequate security?",
            ".A larm system?",
            ". Burglar bars?",
            ". Lockable gates?",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the Facility have the following policies",
            "Supplies and purchasing",
            "Management of epired supplies",
            "Does the Facility have adequate supplies for services provided/",
            "Is there a stock control system?",
        ]
    },
    "CUSTOMER SATISFACTION": {
        "showOnly": [
            "Is there a customer feedback mechanism",
            "Suggestion bo",
            "Customer surveys",
            "Is there a patient charter in both English and Setswana",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
        ]
    },
    "ULTRASOUND ROOM": {
        "showOnly": [
            "Is there evidence of facility liason with the Primary Health Care Department? (A guide the reports to be submitted available)",
            "Is there evidence of statistical reporting to the Primary Health Care Departments as per available guideline?",
        ]
    },

};

export default ObstetricsandGynaecology;
