/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-09-21 23:13:46
 * Facility Type: Hospital
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Hospital = {
    "ENVIRONMENT": {
        "showOnly": [
            "Does The Facility Have Wheelchair Accessibility Or Elevators?",
            "Where There Are Ramps, Are There Safety Features?",
            "Is It Fenced, Secure And Easily Accessible",
            "Is There Adequate Space For Parking?",
            "Is Facility Area Clean And Neat?",
            "Are Surfaces Free From Dust?",
            "Is There Adequate Lighting?",
            "Is Air Conditioning Available?",
            "Is There Enough Ventilation?",
            "Is Flooring Of Cleanable, Smooth Impervious Material?",
            "Are There Relevant Restriction Signs",
            "Is There Parking Space Designated For People Living With Disability?",
            "Is There Directional Signage Within And Outside The Facility?",
            "Is There Backup System For Electricity And Water?",
            "Is There Provision For Water Testing?",
        ]
    },
    "RECEPTION AREA": {
        "showOnly": [
            "Does Reception Area Have Adequate Space?",
            "Is The Telephone Or Cell Phone Available?",
            "Is A Reception Desk With Chair Available",
            "Is There A Computer?",
            "Is It Manned At All Times?",
            "Is There An Organized Patient Registration, Screening, And Booking System",
            "Are There Adequate Patient Benches / Chairs?",
            "Is There A Waste Bin With A Lid?",
            "Is There A Displayed Setswana And English Patient Charter?",
            "Is There Available Drinking Source?",
            "Is There Information Available On The Hazards Of Radiation In The Reception?",
            "Are Educational Materials Available For Clients?",
        ]
    },
    "SCREENING ROOM": {
        "showOnly": [
            "Does The Screening Room Have Adequate Space?",
            "Does The Screening Room Have Wheelchair Accessibility?",
            "Is The Screening Room Equipped With?--",
            "Chairs And Table",
            "Sphygmonometer (Adults & Paediatrics)",
            "Thermometer",
            "Glucometer And Strips",
            "Alcohol Swabs",
            "Weighing Scale",
            "Height Measuring Device",
            "Non Sterile Gloves",
            "Clinical Waste Bins With Lids",
            "Domestic Waste Bin With Lids",
            "Sharp Containers",
            "Hand Wash Facilities",
            "Appropriate Hand Drying Facilities",
        ]
    },
    "CONSULTATION ROOM": {
        "showOnly": [
            "Does The Consultation Room Have Adequate Space?",
            "Does The Consultation Room Have Wheelchair Accessibility?",
            "Does The Consultation Room Have The Following?--",
            "At Least 3 Chairs",
            "Table",
            "Examination Couch With Tiltable Headrest, Covered With Linen",
            "Examination/Treatment Couch Covered With Clean Linen",
            "Is The Couch Behind A Curtain Or Located Within A Screened Off Alcove To Provide Privacy",
            "Steps To Ease Access To Couch",
            "Cabinet/Storage Space",
            "Examination Lamp*",
            "Sterile Gloves",
            "Sphygmomanometer*(Both Adult And Paediatric)",
            "Thermometer",
            "Glucometer* And Strips",
            "Alcohol Swabs",
            "Weighing Scale ( Adult And Paediatric)*",
            "Height Measuring Device*",
            "Non Sterile Gloves",
            "Clinical Waste Bins With Lids",
            "Domestic Waste Bin With Lids",
            "Sharps Container",
            "Appropriate Hand Washing Facilities",
            "Appropriate Hand Drying Facilities",
            "Disposable Cups",
            "Diagnostic Set*",
            "Pen Torch*",
            "Patellar Hammer",
            "Vaginal Speculae (Different Sizes)",
            "Tongue Depressors",
            "X Ray Viewing Box*",
            "Reference Material",
            "Examination Chair",
            "Otoscope Set",
            "Head Light / Head Mirror",
            "Irrigator",
            "Curette",
            "Cone And Thudichum Speculum (Nasal And Ear Speculum)",
            "Tuning Fork",
            "Laryngoscope",
            "Endoscope And Endoscopic Light",
            "Autoclave",
            "Audiometer",
            "Sound Proof Room/ Booth",
            "Siegelï¿½S Speculum",
            "Jobson-Horneï¿½S Probe",
            "Suction Apparatus",
            "Ear Microscope",
            "Dental Chair Covered With Head Rest And All Attachment",
            "Dental Stools",
            "Storage Space For Dental Consumables",
            "Mouth Gargle",
            "Phoropter",
            "Snellen Chart (6 Meters From Client)",
            "Slit Lamp",
            "Stool",
            "Retinal Camera",
            "Binocular Indirect Ophthalmoscope",
            "Direct Ophthalmoscope",
            "Manual Keratometer",
            "Autorefrator",
            "Tonometer",
            "Lensometer",
            "Toric Marker",
            "Pre Chopper",
            "Spectacles",
            "Speculum",
            "Needle Holders",
            "Forceps",
            "Bead Bath Heater",
            "Emergency Tray",
            "Is The Room Sound Proof",
            "Is There Restriction Sign",
            "Tissues",
            "Hiv Testing Kit",
            "Is Psychology Testing Material Available (Intellectual Test)",
            "Wash Basin With Running Hot And Cold Water",
            "Appropriate Soap Dispenser",
            "Cotton Wool/Wipes",
            "Pap Smear Test Kit (Brush, Fixator, Frosted Microscope Glass Slides)",
            "Ultra Sound Machine*",
            "Ultra Sound Jelly",
            "Drip Stand",
            "Emergency Tray",
            "Condoms",
            "Fetoscope",
            "Foetal Monitor",
            "Tape Measure",
            "Sanitary Pads",
            "Stool",
            "Lubricating Jell Or Solution",
        ]
    },
    "PROCEDURE ROOM": {
        "showOnly": [
            "Does The Procedure Room Have Adequate Space?",
            "Is The Procedure Room Wheelchair Accessible?",
            "Does The Procedure Room Have The Following?--",
            "A Fully Equipped Resuscitation Trolley Which Is Regularly Checked",
            "Chairs",
            "Examination Couch With Tiltable Headrest, Covered With Linen",
            "Is There Couch Behind A Curtain Or Located Within A Screened Off Alcove To Provide Privacy",
            "Steps To Ease Access To Couch",
            "Cupboards And Suitably Surfaced Bench Tops",
            "Examination Lamp*",
            "Sterile Gloves",
            "Sphygmomanometer*(Both Adult And Paediatric)*",
            "Non Sterile Gloves",
            "Sharps Container",
            "Hand Wash Facilities",
            "Appropriate Hand Drying Facilities",
            "Basin With Running Water And Soap Dispenser?",
            "Drip Stand",
            "X-Ray View Box",
        ]
    },
    "BLEEDING ROOM": {
        "showOnly": [
            "Does The Bleeding Room Have Adequate Space?",
            "Does The Room Have Wheelchair Accessibility?",
            "Does The Lab Have Procedures For Patient Preparation Before Blood Collection?",
            "Is The Room Equipped With The Following--",
            "2 Or More Chairs",
            "Blood Tubes Of Different Colours",
            "Needles And Syringes (Different Sizes)",
            "Vacutainer",
            "Tourniquet (Adults And Peads)",
            "Plaster",
            "Cotton Swab",
            "Sharps Container",
            "Antiseptic Disinfectant",
            "Clinical Waste Bin With Lid",
            "Domestic Waste Bin With Lid",
            "Hand Wash Facilities",
            "Appropriate Hand Drying Facilities",
            "Disposable Gloves",
            "Ice Packs",
            "Specimen Racks",
            "Ï¿½ Hand Basin With Running Water And Suitable Soap Dispenser?",
            "Cooler Box",
            "Alcohol Swab",
            "Specimen Register/Computer",
            "Specimen Containers",
            "Is There Provision For Patient Privacy",
            "Is There Air-Conditioner With Monitoring Device And Chart?",
        ]
    },
    "SLUICE ROOM": {
        "showOnly": [
            "Does The Sluice Room Have Adequate Space?",
            "Does The Room Have Adequate Ventilation?",
            "Is The Sluice Room Equipped With The Following--",
            "Stainless Steel Sink With Running Water",
            "Stainless Steel Washing Sink With Running Water?",
            "Stainless Steel Waste Discarding Sink",
            "Non-Sterile Gloves?",
            "Heavy Duty Gloves",
            "Disinfectant",
            "Waste Bin With Lid For Clinical Waste?",
            "Waste Bin With Lid For Non-Clinical Waste",
            "Linen Canvas Bag Or Trolley (Soiled Or Non Soiled)",
            "Racks For Sputum Mugs, Urinals",
        ]
    },
    "TOILET FACILITITES": {
        "showOnly": [
            "Is There A Minimum Of Two Toilets Available (For Male And",
            "Female Patients)?",
            "Are They Labelled Ï¿½Maleï¿½ And Ï¿½Female?Ï¿½",
            "Are Toilets Fitted With Hand Wash Facilities?",
            "Is There Suitable Soap Dispenser?",
            "Is There An Appropriate Hand Drying Provision?",
            "Is There A Separate Toilet For Staff?",
            "Is There A Toilet That Is Designed For Wheel Chair Users?",
            "Are Toilets Wheel Chair Accessible?",
            "Does The Female Toilet Have Sanitary Pads Disposal?",
            "Are Toilets Aesthetically Pleasing?",
            "Is There Provision For Paediatric Clients?",
        ]
    },
    "RECORDS/ INFORMATION MANAGEMENT": {
        "showOnly": [
            "Are Patients Records Well Maintained?",
            "Is There A Policy On Patient Confidentiality?",
            "Are Records Controlled And Safe From Manipulation?",
            "Are Records Kept Electronically?",
            "Is There A Backup System For Electronic Data?",
            "If Hard Copies Are Kept, Is There A System For Protection Against Damage?",
            "Is There A Policy On Record Retention Times?",
            "Are Hard Copies Kept In A Lockable Cabinet For Maximum Security?",
        ]
    },

};

export default Hospital;
