/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-09-13 07:43:05
 * Facility Type: Clinic
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Clinic = {
    "ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?",
            "Does the facility have statutory requirements?--",
            "work permits for staff",
            "lease agreement",
            "business registration",
            "trade licence",
            "contracts for staff",
            "occupancy certificate",
            "letter of permission to set up/operate",
            "waste collection carrier licence",
            "police clearance for employees",
            "Confidentiality clause",
            "proof of change of land use fire clearance",
            "resident permit",
            "Copies of statutory",
            "indemnity Insuarance",
            "Copies of relevant statutory instruments e.g. Public Health Act 2013, Botswana Health Professions Act,2001",
            "Is there indemnity insurance?",
            "Does the clinic have policies and procedures for the following?--",
            "patient consent",
            "Patients referral",
            "assessment of patients",
            "testing and treatment techniques",
            "management of high risk patients",
            "confidentiality of patient information",
            "incident reporting",
            "Orientation and induction",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "treatment protocols/Guidelines",
            "incident reporting",
            "Infection prevention and control",
            "Management of patient records and retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post exposure prophylaxis",
            "Complaints procedure",
            "Outreach services",
            "Waste management",
        ]
    },
    "SERVICE PROVIDED": {
        "showOnly": [
            "What are the services provided at the facility?--",
            "Specialists services (Specify)",
            "Specimen collection (specify)",
            "General Practice",
            "Laboratory services(specify)",
            "Pharmaceutical services (specify)",
            "Others (Specify)",
            "Any outreach services? If yes",
            "Is there letter of permission to offer the outreach services",
            "Is there proof of agreement? Agreement letter with the facility where services will be offered from",
            "Is there provision of emergency contact numbers?",
            "Are the service to be provided displayed?",
            "Are emergency contact numbers displayed?",
            "What is number of patients seen per month?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff?",
            "What is the current total number of staff?",
            "Medical Doctors",
            "Specialist doctors",
            "Nurses",
            "pharmacists",
            "Pharmacy technicians",
            "Laboratory scientists",
            "Laboratory technicians",
            "Administrative",
            "Support staff",
            "Other (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Personnel Files have the following? --",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentially clause",
            "Evidence of orientation and induction",
            "Evidence of continued education",
            "Signed contracts or offer letters",
            "Medical examination certificates",
        ]
    },
    "ENVIRONMENT": {
        "showOnly": [
            "Does the facility have wheelchair accessibility or elevators?",
            "Where there are ramps, are there safety features?",
            "Is it fenced, secure and easily accessible",
            "Is there adequate space for parking?",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there adequate lighting?",
            "Is air conditioning available?",
            "Is there enough ventilation?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs",
            "Is there parking space designated for people living with disability?",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity and water?",
            "Is there provision for water testing?",
        ]
    },
    "RECEPTION AREA": {
        "showOnly": [
            "Does reception area have adequate space?",
            "Is the telephone or cell phone available?",
            "Is a reception desk with chair available",
            "Is there a computer?",
            "Is it manned at all times?",
            "Is there an organized Patient registration, Screening, and booking system",
            "Are there adequate patient benches / chairs?",
            "Is there a waste bin with a lid?",
            "Is there a displayed Setswana and English patient charter?",
            "Is there available drinking source?",
            "Is there information available on the hazards of radiation in the reception?",
            "Are educational materials available for clients?",
        ]
    },
    "SCREENING ROOM": {
        "showOnly": [
            "Does the screening room have adequate space?",
            "Does the screening room have wheelchair accessibility?",
            "Is the screening room equipped with?--",
            "Chairs and table",
            "Sphygmonometer (adults & Paediatrics)",
            "Thermometer",
            "Glucometer and strips",
            "Alcohol Swabs",
            "Weighing scale",
            "Height measuring device",
            "Non sterile gloves",
            "Clinical waste bins with lids",
            "Domestic waste bin with lids",
            "Sharp containers",
            "Hand wash facilities",
            "Appropriate Hand drying facilities",
        ]
    },
    "CONSULTATION ROOM": {
        "showOnly": [
            "Does the consultation room have adequate space?",
            "Does the consultation room have wheelchair accessibility?",
            "Does the consultation room have the following?--",
            "At least 3 Chairs",
            "Table",
            "Examination couch with tiltable headrest, covered with linen",
            "Examination/treatment couch covered with clean linen",
            "Is the couch behind a curtain or located within a screened off alcove to provide privacy",
            "Steps to ease access to couch",
            "Cabinet/Storage space",
            "Examination lamp*",
            "Sterile gloves",
            "Sphygmomanometer*(both adult and paediatric)",
            "Thermometer",
            "Glucometer* and strips",
            "Alcohol swabs",
            "Weighing scale ( adult and paediatric)*",
            "Height measuring device*",
            "Non sterile gloves",
            "clinical waste bins with lids",
            "domestic waste bin with lids",
            "Sharps container",
            "Appropriate hand washing facilities",
            "Appropriate hand drying facilities",
            "Disposable cups",
            "Diagnostic set*",
            "Pen torch*",
            "Patellar hammer",
            "Vaginal speculae (different sizes)",
            "Tongue depressors",
            "X ray viewing box*",
        ]
    },
    "PROCEDURE ROOM": {
        "showOnly": [
            "Does the procedure room have adequate space?",
            "Is the procedure room wheelchair accessible?",
            "Does the procedure room have the following?--",
            "Chairs",
            "Examination couch with tiltable headrest, covered with linen",
            "Is there couch behind a curtain or located within a screened off alcove to provide privacy",
            "Steps to ease access to couch",
            "Cupboards and suitably surfaced bench tops",
            "Examination lamp*",
            "Sterile gloves",
            "Sphygmomanometer*(both adult and paediatric)*",
            "Alcohol swabs",
            "Non sterile gloves",
            "clinical waste bins with lids",
            "domestic waste bin with lids",
            "Sharps container",
            "Hand wash facilities",
            "Appropriate hand drying facilities",
            "Vaginal speculae",
            "Tongue depressors",
            "Drip stand",
            "Nebulizing machine and solutions",
            "Sterile suture pack (gale pots, needle holder, scalpel, pair of stich scissors, tooth forceps)",
            "Sterile dressing packs (sponge holding forceps, toothed and non-toothed forceps, straight artery forceps, 2 galley pots, sterile gauge and cotton wool swabs, kidney dish, scalpel)",
            "bandages and plasters",
            "disinfectants or antiseptic solutions",
            "Normal saline",
            "Antiseptic ointments, creams, solutions etc.",
            "Needles (different sizes)",
        ]
    },
    "BLEEDING ROOM": {
        "showOnly": [
            "Does the bleeding room have adequate space?",
            "Does the room have wheelchair accessibility?",
            "Is the room equipped with the following--",
            "2 or more Chairs",
            "Blood tubes of different colours",
            "Needles and syringes (different sizes)",
            "Vacutainer",
            "Tourniquet (adults and peads)",
            "Plaster",
            "Cotton swab",
            "sharps container",
            "Antiseptic Disinfectant",
            "Clinical waste bin with lid",
            "Domestic waste bin with lid",
            "Hand wash facilities",
            "Appropriate hand drying facilities",
            "Disposable gloves",
            "Ice packs",
            "Specimen racks",
        ]
    },
    "SLUICE ROOM": {
        "showOnly": [
            "Does the sluice room have adequate space?",
            "Does the room have adequate ventilation?",
            "Is the sluice room equipped with the following--",
            "Stainless steel sink with running water",
            "Stainless steel washing sink with running water?",
            "Stainless steel waste discarding sink",
            "Non-sterile gloves?",
            "Heavy duty gloves",
            "Disinfectant",
            "Waste bin with lid for clinical waste?",
            "Waste bin with lid for non-clinical waste",
            "Linen Canvas Bag or Trolley (Soiled or non soiled)",
            "Racks for sputum mugs, urinals",
        ]
    },
    "TOILET FACILITITES": {
        "showOnly": [
            "Is there a minimum of two toilets available (for male and",
            "Female patients)?",
            "Are they labelled male and female?",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Are toilets wheel chair accessible?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
        ]
    },
    "PHARMACY/ DISPENSARY": {
        "showOnly": [
            "Is there a pharmacy personnel employed to carry out the pharmacy functions?",
            "Does the dispensary have adequate space to allow for an efficient workflow?",
            "Are there adequate shelves for stock keeping?",
            "Is stock arranged and labelled in a systematic manner?",
            "Are drugs well protected from direct sunlight?",
            "Are all surfaces finished with an impervious washable material?",
            "Are all surfaces in a good state of repair?",
            "is there a lockable refrigerator for the storage of thermos-labile drugs?",
            "Are there mechanisms in place for monitoring and controlling room temperatures (storage and dispensary)?",
            "Are there mechanisms in place for monitoring and controlling refrigerator temperatures?",
            "Is the sink supplied with hot and cold water?",
            "Are the floors, walls, ceiling and shelves kept satisfactorily clean?",
            "Is there a suitable of lighting in the dispensary?",
            "Is there a suitable means for counting tablets and capsules dispensed?",
            "Is there a suitable means of measuring liquids dispensed?",
            "Is the preparation room clean as per the requirements?",
            "Are there suitable ranges of containers for the dispensing of--",
            "Tablets/capsules",
            "liquids",
            "Cream/ointments",
            "Are there suitable labels for the above mentioned",
            "Is there a register for drugs of schedule 1A, 1B and 1C?",
            "Is there a lockable cabinet for the storage of 1A and 1B drugs?",
            "Is there a policy for the management of expired drugs?",
            "Is there adequate security in the dispensary?",
            "Is there a stock management system?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does the Facility have a policy on waste management?",
            "Does the clinic have SOPs on waste management?",
            "Does the clinic have a waste disposal system? Specify:--",
            "Domestic Waste",
            "Clinical Waste",
            "Other waste",
            "Does the clinic have a policy and procedures on safety?",
            "Is there a policy and procedure on accidental exposure to HIV?",
            "Does the clinic have fire protection equipment?--",
            "Fire extinguishers",
            "Emergency exits",
            "Additional:--",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the clinic have a written program for maintaining fire protection equipment",
            "Fire inspection report?",
            "Does the clinic have adequate security?",
            "Alarm system?",
            "Burglar bars?",
            "Lockable gates?",
            "Others--",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the clinic have the following policies--",
            "supplies and purchasing",
            "management of expired supplies",
            "Does the clinic have adequate supplies for services provided?",
            "Is there a stock control system? If yes explain",
        ]
    },
    "RECORDS/ INFORMATION MANAGEMENT": {
        "showOnly": [
            "Are patients records well maintained?",
            "Is there a policy on patient confidentiality?",
            "Are records controlled and safe from manipulation?",
            "Are records kept electronically?",
            "Is there a backup system for electronic data?",
            "If hard copies are kept, is there a system for protection against damage?",
            "Is there a policy on record retention times?",
            "Are hard copies kept in a lockable cabinet for maximum security?",
        ]
    },
    "CUSTOMER SATISFACTION": {
        "showOnly": [
            "Is there a customer feedback mechanism--",
            "Suggestion box",
            "Customer surveys",
            "Others",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
        ]
    },

};

export default Clinic;
