/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-09-13 07:43:05
 * Facility Type: Laboratory
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Laboratory = {
    "ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?",
            "Does the facility have statutory requirements?--",
            "work permits for staff",
            "lease agreement",
            "business registration",
            "trade licence",
            "contracts for staff",
            "occupancy certificate",
            "letter of permission to set up/operate",
            "waste collection carrier licence",
            "police clearance for employees",
            "Confidentiality clause",
            "proof of change of land use fire clearance",
            "resident permit",
            "Copies of statutory",
            "indemnity Insuarance",
            "Copies of relevant statutory instruments e.g. Public Health Act 2013, Botswana Health Professions Act,2001",
            "Is there indemnity insurance?",
            "Does the clinic have policies and procedures for the following?--",
            "patient consent",
            "Patients referral",
            "assessment of patients",
            "testing and treatment techniques",
            "management of high risk patients",
            "confidentiality of patient information",
            "incident reporting",
            "Orientation and induction",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "treatment protocols/Guidelines",
            "incident reporting",
            "Infection prevention and control",
            "Management of patient records and retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post exposure prophylaxis",
            "Complaints procedure",
            "Outreach services",
            "Waste management",
        ]
    },
    "SERVICE PROVIDED": {
        "showOnly": [
            "What are the services provided at the facility?--",
            "Specialists services (Specify)",
            "Specimen collection (specify)",
            "Others (Specify)",
            "What is number of specimens tested per month?",
            "Any outreach services? If yes",
            "Is there letter of permission to offer the outreach services",
            "Is there proof of agreement? Agreement letter with the facility where services will be offered from",
            "Is there provision of emergency contact numbers?",
            "Are the service to be provided displayed?",
            "Are emergency contact numbers displayed?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff?",
            "What is the current total number of staff?",
            "How many will be?--",
            "Specialist doctors",
            "Laboratory scientists",
            "Laboratory technicians",
            "Administrative",
            "Support staff",
            "Other (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Personnel Files have the following? --",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentially clause",
            "Evidence of orientation and induction",
            "Evidence of continued education",
            "Signed contracts or offer letters",
            "Medical examination certificates",
        ]
    },
    "ENVIRONMENT": {
        "showOnly": [
            "Does the facility have wheelchair accessibility or elevators?",
            "Where there are ramps, are there safety features?",
            "Is it fenced, secure and easily accessible",
            "Is there adequate space for parking?",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there adequate lighting?",
            "Is air conditioning available?",
            "Is there enough ventilation?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs",
            "Is there parking space designated for people living with disability?",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity and water?",
            "Is there provision for water testing?",
        ]
    },
    "RECEPTION AREA": {
        "showOnly": [
            "Is there provision for generator testing if available",
            "Does reception area have adequate space?",
            "Is the telephone or cell phone available?",
            "Is a reception desk with chair available",
            "Is there a computer?",
            "Is it manned at all times?",
            "Is there an organized Patient registration, Screening, and booking system",
            "Are there adequate patient benches / chairs?",
            "Is there a waste bin with a lid?",
            "Is there a displayed Setswana and English patient charter?",
            "Is there available drinking source?",
            "Is there information available on the hazards of radiation in the reception?",
            "Are educational materials available for clients?",
        ]
    },
    "BLEEDING ROOM": {
        "showOnly": [
            "Does the bleeding room have adequate space?",
            "Does the room have wheelchair accessibility?",
            "Does the lab have procedures for patient preparation before blood collection?",
            "Is the room equipped with the following--",
            "2 or more Chairs",
            "Blood tubes of different colours",
            "Needles and syringes (different sizes)",
            "Vacutainer",
            "Tourniquet (adults and peads)",
            "Plaster",
            "Cotton swab",
            "sharps container",
            "Antiseptic Disinfectant",
            "Clinical waste bin with lid",
            "Domestic waste bin with lid",
            "Hand wash facilities",
            "Appropriate hand drying facilities",
            "Disposable gloves",
            "Ice packs",
            "Specimen racks",
            "· Hand basin with running water and suitable soap dispenser?",
            "Cooler box",
            "Alcohol swab",
            "Specimen register/computer",
            "Specimen containers",
            "Is there provision for patient privacy",
            "Is there air-conditioner with monitoring device and chart?",
        ]
    },
    "TOILET FACILITITES": {
        "showOnly": [
            "Is there a minimum of two toilets available (for male and",
            "Female patients)?",
            "Are they labelled male and female?",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Are toilets wheel chair accessible?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
        ]
    },
    "SPECIMEN ROOM": {
        "showOnly": [
            "Does the room have the following:--",
            "Chairs and a table",
            "Disposable gloves",
            "Specimen racks and trays",
            "Specimen register/computer",
            "Markers/stickers",
            "Sharps container",
            "Waste bin with lid for clinical waste",
            "Waste bin with lid for domestic waste",
            "Is there an organised specimen registration system?",
            "Does registration use a unique patient identification",
            "Is there identification kept throughout lab testing",
            "Is there provision for patient privacy?",
            "Is there documented specimen acceptance/rejection criteria",
            "Does the lab have a documented specimen system( collection, handling, storage and transportation",
            "Is there specimen fridge with temperature monitoring device and chart",
            "Is there air-conditioner with monitoring device and chart?",
        ]
    },
    "LAB SERVICES PROVIDED": {
        "showOnly": [
            "Chemistry--",
            "Does the testing area have adequate space?",
            "Are there adequate lab stools and benches?",
            "Is there hand washing provision?",
            "Is there air-conditioner with monitoring device and chart?",
            "List the clinical chemistry tests done by the lab:",
            "Does the lab have Technical SOPs (test methods)?",
            "Does the lab have the following equipment--",
            "Chemistry analyser",
            "Centrifuge",
            "Medical fridge",
            "Medical freezer",
            "Graduated Pipettes",
            "Automated Pipettes",
            "Water distiller or provision for distilled water",
            "Are normal and abnormal Quality Control done and recorded",
            "How often are Quality controls run?",
            "Are QC results monitored over a period of time?",
            "Does the lab participate in External Quality Assessment Schemes?",
            "Are EQA results reviewed and monitored?",
            "Does the lab have Reference Ranges for the tests performed?",
            "Are refrigerator and freezer temperatures monitored?",
            "Waste bin with lid for clinical waste",
            "Waste bin with lid for domestic waste",
            "Are reagents stored appropriately? Explain",
            "Are lab equipment calibrated",
            "Is there an equipment preventative maintenance plan?",
            "Is expiry of items monitored?",
            "Haematology:--",
            "Does the testing area have adequate space?",
            "Are there adequate lab stools and benches?",
            "Is there hand washing provision?",
            "Is there air-conditioner with monitoring device and chart?",
            "List clinical tests done at Haematology",
            "Does the lab have Technical SOPs (test methods)?",
            "Does the lab have the following equipment--",
            "Haematology analyser?",
            "Microscope?",
            "Staining Racks?",
            "Water bath?",
            "Coagulation machine?",
            "ESR tubes and caps?",
            "Sample Rocker?",
            "Medical fridge?",
            "Sample rotator?",
            "Automated Pipettes?",
            "Graduated Pipettes?",
            "Pipette Fillers?",
            "Are normal and abnormal Quality Control done and recorded?",
            "How often are Quality controls run?",
            "Are QC results monitored over a period of time?",
            "Does the lab participate in External Quality Assessment Schemes?",
            "Are EQA results reviewed and monitored?",
            "Does the lab have Reference Ranges for the tests performed?",
            "Are refrigerator and freezer temperatures monitored?",
            "Waste bin with lid for clinical waste",
            "Waste bin with lid for domestic waste",
            "Are reagents stored appropriately? Explain",
            "Are lab equipment calibrated",
            "Is there an equipment preventative maintenance plan?",
            "Is expiry of items monitored?",
            "Microbiology:--",
            "Does the testing area have adequate space?",
            "Are there adequate lab stools and benches?",
            "Is there air-conditioner with monitoring device and chart?",
            "Is there hand washing provision?",
            "List clinical tests done at microbiology:",
            "Does the lab have Technical SOPs (test methods",
            "Does the lab have the following equipment:--",
            "Incubators(CO2,O2,42OC)",
            "Microscopes?",
            "Autoclave?",
            "Anaerobic Jars?",
            "Wire loops",
            "Disposable Inoculating loops and needles?",
            "Urine wire loop",
            "Reading lamp",
            "Centrifuge?",
            "Vortex",
            "Staining racks?",
            "Sample rocker?",
            "Medical fridge",
            "Medical freezer?",
            "Hot plate?",
            "Weighing scale?",
            "Bunsen burner?",
            "Gas cylinders?",
            "Autoclave?",
            "Timers?",
            "Reagent bottles(brown)?",
            "Measuring Cylinders?",
            "Conical flasks?",
            "Reagent Preparation Bottles?",
            "Universal Bottles?",
            "Bijou bottles?",
            "Graduated Pipettes?",
            "Storage cabinet for flammables?",
            "Urine centrifuge tubes?",
            "Ready to use culture media?",
            "Ready to use staining reagents?",
            "Graduated Pipettes?",
            "How often are QC run?",
            "Does the lab have Quality Control Organisms?",
            "How often are QC run?",
            "Are QC results monitored over a period of time?",
            "Does the lab participate in EQA Assessment Schemes?",
            "Are EQA results reviewed and monitored?",
            "Are refrigerator temperatures monitored?",
        ]
    },
    "HIV SCREENING": {
        "showOnly": [
            "Does the lab do any HIV screening?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does the Facility have a policy on waste management?",
            "Does the clinic have SOPs on waste management?",
            "Does the clinic have a waste disposal system? Specify:--",
            "Domestic Waste",
            "Clinical Waste",
            "Other waste",
            "Does the clinic have a policy and procedures on safety?",
            "Is there a policy and procedure on accidental exposure to HIV?",
            "Does the clinic have fire protection equipment?--",
            "Fire extinguishers",
            "Emergency exits",
            "Additional:--",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the clinic have a written program for maintaining fire protection equipment",
            "Fire inspection report?",
            "Does the clinic have adequate security?",
            "Alarm system?",
            "Burglar bars?",
            "Lockable gates?",
            "Others--",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the clinic have the following policies--",
            "supplies and purchasing",
            "management of expired supplies",
            "Does the clinic have adequate supplies for services provided?",
            "Is there a stock control system? If yes explain",
        ]
    },
    "RECORDS/ INFORMATION MANAGEMENT": {
        "showOnly": [
            "Are patients records well maintained?",
            "Is there a policy on patient confidentiality?",
            "Are records controlled and safe from manipulation?",
            "Are records kept electronically?",
            "Is there a backup system for electronic data?",
            "If hard copies are kept, is there a system for protection against damage?",
            "Is there a policy on record retention times?",
            "Are hard copies kept in a lockable cabinet for maximum security?",
        ]
    },
    "CUSTOMER SATISFACTION": {
        "showOnly": [
            "Is there a customer feedback mechanism--",
            "Suggestion box",
            "Customer surveys",
            "Others",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
        ]
    },

};

export default Laboratory;
