/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist-final.csv
 * Generated on: 2026-01-07 18:53:29
 * Facility Type: Emergency Medical Services
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const EmergencyMedicalServices = {
    "SECTION A-ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?--",
            "Business registration",
            "Tax clearance certificate",
            "Valid private pactice license",
            "Work permits",
            "residence permit",
            "Lease agreement",
            "Occupancy certificate",
            "Permission to operate/set up",
            "Patient charter in English & Setswana",
            "Is there an indemnity insurance?",
            "contracts for staff",
            "Police Clearance",
            "waste collection carrier licence",
            "confidentiality clause",
            "proof of change of land use",
            "Practitioners licence",
            "Fire clearance",
            "Contracts for outsourced services",
            "Patient referral",
            "Assessment of patients",
            "Management of high risk patients",
            "The confidentiality of patient information",
            "Incident reporting",
            "Induction and orientation",
            "Patient consent",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "Infection prevention and control",
            "Management of patient records",
            "Record retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post exposure prophylaxis",
            "Complaints procedure",
            "Disaster preparedness",
            "Waste management",
            "Others",
            "Treatment protocols/ guidelines",
            "Testing and treatment techniques",
            "Copies of relevant statutory instruments",
        ]
    },
    "SERVICES PROVIDED": {
        "showOnly": [
            "What are the services provided at the Facility?--",
            "General services; Specify",
            "Specialist services; Specify",
            "Other services (Specify);",
            "Are hours of operation displayed?",
            "State hours of operation",
            "Are emergency contact numbers displayed?",
            "What is number of patients seen/ Samples received per month",
            "Any outreach services? If yes state them.",
            "Is there permission to offer the outreach services",
            "Agreement letter with a doctor where outreach services will be offered from",
            "Is there provision of emergency outreach services?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff",
            "What is the current number of staff--",
            "General Health Professionals (Specify)",
            "Specialists (Specify)",
            "Other (specify)",
            "Administrative Staff (Specify)",
            "Support staff (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentiality clause",
            "Evidence of orientation and induction",
            "Signed contracts or offer letters",
            "Medical eamination certificates",
            "Evidence of continous Professional Development",
        ]
    },
    "FACILITY-ENVIRONMENT": {
        "showOnly": [
            "Does the facility have wheelchair accessibility?",
            "Is it fenced, secure and easily accessible",
            "Is there space for parking? Specify",
            "Is there parking space designated for people living with disability? Specify",
            "Do the facility have space for services provided? Specify",
            "Is there provision for handwashing?",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there lighting in all service areas?",
            "Is air conditioning available?",
            "Is there ventilation in all service area?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs?",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity?",
            "Is there backup system for water?",
            "Where there are ramps, are there safety features?",
        ]
    },
    "OFFICE FOR THE MANAGER": {
        "showOnly": [
            "Is there an office for the In- Charge officer?",
            "Does the oofice have the followig;",
            "Chairs",
            "Table",
            "Desktop/ computer connected to printer?",
            "Telephone",
            "Habit Forming cabinet/ cupboard?",
        ]
    },
    "SLUICE ROOM": {
        "showOnly": [
            "Does the room have space? Elaborate.",
            "Does the room have ventilation? Elaborate",
            "Does the room have wheelchair accessibility?",
            "Is the room equipped with the following--",
            "Canvas bag trolley with cover",
            "Canvas bag trolley with cover for non soiled linen",
            "Canvas bag trolley with cover for soiled linen",
            "clinical waste bins with lid",
            "Disinfectant",
            "Domestic waste bins with lid",
            "Heavy duty gloves",
            "Non sterile gloves",
            "Stainless steel sink with running water",
            "stainless steel waste discarding sink or sluice machine",
        ]
    },
    "TOILET FACILITIES": {
        "showOnly": [
            "Is there a minimum of two toilets available (for male and",
            "Female patients)?",
            "Are they labelled �maleand �female?�",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does the Facility have a policy on waste management?",
            "Does the Facility have SOPs on waste management?",
            "Does the Facility have a waste disposal system? Specify:",
            "Domestic Waste",
            "Clinical Waste",
            "Does the Facility have a policy and procedures on safety?",
            "Is there a policy and procedure on accidental eposure to HIV?",
            "Does the Facility have fire protection equipment?",
            "Fire etinguishers",
            "Emergency eits",
            "Additional:",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the Facility have a written program for maintaining fire protection equipment ?",
            "Does the Facility have adequate security?",
            "A larm system?",
            "Burglar bars?",
            "Lockable gates?",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the Facility have the following policies--",
            "supplies and purchasing",
            "management of expired supplies",
            "Does the Facility have adequate supplies for services provided",
            "Is there a stock control system?",
        ]
    },
    "TENS": {
        "showOnly": [
            "Is there a customer feedback mechanism",
            "Suggestion bo",
            "Customer surveys",
            "Is there a patient charter in both English and Setswana",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
        ]
    },
    "ULTRASOUND ROOM": {
        "showOnly": [
            "Is there evidence of facility liason with the Primary Health Care Department? (A guide the reports to be submitted available)",
            "Is there evidence of statistical reporting to the Primary Health Care Departments as per available guideline?",
        ]
    },
    "FACILITY-CALL CENTRE": {
        "showOnly": [
            "Does reception area have adequate space? Elaborate.",
            "Is the telephone/ cell phone available?",
            "Is the telephone able to record calls",
            "Is a reception desk and chair available",
            "Is it manned at all times?",
            "Is there an organized patient registration, screening and booking system?",
            "Are there adequate patient benches / chairs in the waiting area? Elaborate.",
            "Is there a waste bin?",
            "Is there a computer/ desktop?",
            "Is there patient charter available in Setswana and English?",
            "Is there available drinking water source?",
            "Are educational materials available for clients",
            "Does the EMS have the following?--",
            "Patient acceptance criteria",
            "Patient privacy policy",
            "Male and female changing rooms",
            "Staff room",
            "Ambulances (Road/air/boat)",
            "Heli pad where necessary",
            "Ambulance wash bays",
            "Ambulance service record",
            "Spine immobilization equipment",
            "Vital signs monitoring equipment including but not limited to;--",
            "Patient monitors",
            "Glucometer",
            "Urine dip sticks",
            "Oxygen with flow meters",
            "cricothyroctomy tubes and adapters",
            "Laryngoscopes (varying sizes and shapes)",
            "Ventilation devices (Bag valve mask, oxygen maks)",
            "Endotracheal tubes",
            "Suction tubes",
            "Syringes",
            "Needles",
            "Emergency medications",
            "Complete intraveneous infusion sets",
            "Cannulation equipment",
            "Intra oseous canulation equipment",
            "Suture pack",
            "Foley cathethers",
            "Naso gastric tubes",
            "Oropharyngeal airway",
        ]
    },

};

export default EmergencyMedicalServices;
