/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-11-25 11:54:31
 * Facility Type: Dental
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Dental = {
    "ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?",
            "Does the facility comply with regulatory requirements? --",
            "Business registration",
            "ta clearance certificate",
            "Valid private pactice license",
            "Work permits",
            "Residence permit",
            "Lease agreement",
            "Occupancy certificate",
            "Permission to operate/set up",
            "Patient charter in English & Setswana",
            "Is there an indemnity insurance?",
            "contracts for staff",
            "Police Clearance",
            "letter of permission to set up",
            "waste collection carrier licence",
            "confidentiality clause",
            "proof of change of land use",
            "Practitioners licence",
            "Fire clearance",
            "residence permit",
            "Does the Facility have policies and procedures for the following?--",
            "Patient referral",
            "Assessment of patients",
            "Management of high risk patients",
            "The confidentiality of patient information",
            "Incident reporting",
            "Induction and orientation",
            "Patient consent",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "Infection prevention and control",
            "Management of patient records",
            "Record retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post eposure prophylais",
            "Complaints procedure",
            "Outreach services",
            "Waste management",
            "Does the Facility have the following reference materials?--",
            "Treatment protocols/ guidelines",
            "Testing and treatment techniques",
            "Copies of relevant statutory instruments",
        ]
    },
    "SERVICES PROVIDED": {
        "showOnly": [
            "What are the services provided at the Facility?--",
            "General services; Specify",
            "Specialist services; Specify",
            "Other services (Specify); .....",
            "Is there a services board within the facility?",
            "Are hours of operation displayed?",
            "State hours of operation",
            "Are emergency contact numbers displayed?",
            "What is number of patients seen/ Samples received per month",
            "Any outreach services? If yes state them.",
            "Is there permission to offer the outreach services",
            "Agreement letter with a doctor where outreach services will be offered from",
            "Is there provision of emergency outreach services?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff",
            "What is the current number of staff--",
            "General Health Professionals (Specify)",
            "Specialists (Specify)",
            "Other (Specify)",
            "Administrative Staff (Specify)",
            "Support staff (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Did personnel files have the following?--",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentiality clause",
            "Evidence of orientation and induction",
            "Evidence of continued education",
            "Signed contracts or offer letters",
            "Medical eamination certificates",
            "Evidence of continous Professional Development",
            "Does the facility have wheelchair accessibility?",
            "Is it fenced, secure and easily accessible",
            "Is there space for parking? Specify",
            "Is there parking space designated for people living with disability? Specify",
            "Do the facility have space for services provided? Specify",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there lighting in all service areas?",
            "Is air conditioning available?",
            "Is there ventilation in all service area?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity?",
            "Is there backup system for water?",
            "Where there are ramps, are there safety features?",
            "Does reception area have space? Elaborate.",
            "Is the telephone/ cell phone available?",
            "Is a reception desk with chair available",
            "Is it manned at all times?",
            "Is there an organized patient registration, screening and booking system",
            "Are there patient benches / chairs in the waiting area? Elaborate.",
            "Is there a waste bin?",
            "Is there a computer/ desktop?",
            "Is there patient charter available in Setswana and English?",
            "Is there available drinking water source?",
            "Are educational materials available for clients",
            "Does the screening room have space? Elaborate.",
            "Does the screening room have wheelchair accessibility?",
            "Is screening room equipped with the following?--",
            "Chairs and table",
            "Sphygmomanometer",
            "Thermometer",
            "Glucometer and strips",
            "Alcohol Swabs",
            "Weighing scale (both adult and paediatric)",
            "Height measuring device",
            "Non sterile gloves",
            "Clinical waste bin with lid",
            "Domestic waste bin with lid",
            "Sharps container",
            "Hand wash facilities",
            "Appropriate hand drying facilities",
            "Appropriate hand wash soap",
            "Does the consultation room have adequate space?",
            "Does the consultation room have wheelchair accessibility",
            "Does the consultation room have the following --",
            "At least 3 Chairs",
            "Alcohol swabs",
            "Appropriate hand drying facilities",
            "Appropriate soap dispenser",
            "Autoclave",
            "Cabinet/Storage space",
            "clinical waste bin with lid",
            "Cotton swabs soaked in alcohol",
            "Cotton wool/ wipes",
            "Curette",
            "Dental chair with headrest and all attachments",
            "Dental stools",
            "Diagnostic set*",
            "disposable cups",
            "Disposable gloves",
            "domestic waste bin with lid",
            "Emergency tray",
            "Eamination chair",
            "Eamination/ treatment couch with tiltable headrest behind a curtain, covered with linen",
            "Eamination/ treatment couch behind a curtain or located within a screen off aclove to provide privacy?",
            "Eamination/ treatment couch covered with linen?",
            "Eamination lamp*",
            "Forceps",
            "Glucometer* and strips",
            "Hand washing basin with running hot and cold water",
            "Hand washing soap",
            "hand drying facilities",
            "Height measuring device",
            "HIV testing kit",
            "Mouth gargle",
            "Needle holders",
            "Non sterile gloves",
            "Reference material",
            "Sharps container",
            "Sphygmomanometer*",
            "Sterile gloves",
            "Storage space for consumables",
            "Suction apparatus",
            "Tape measure",
            "Thermometer*",
            "Tongue depressors",
            "Ultra sound jelly",
            "Waste bin with lids for domestic waste",
            "Waste bins with lids for clinical waste",
            "Weighing scale (both adult and paediatric)*",
            "-ray viewing bo",
            "Toilet facilities--",
            "Is there a minimum of two toilets available (for male and",
            "Female patients)?",
            "Are they labelled male and female?",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Are toilets wheel chair accessible?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
            "Safety and waste management --",
            "Does the Facility have a policy on waste management?",
            "Does the Facility have SOPs on waste management?",
            "Does the Facility have a waste disposal system? Specify:",
            ". Domestic Waste",
            ". Clinical Waste",
            ". Does the Facility have a policy and procedures on safety?",
            ". Is there a policy and procedure on accidental eposure to HIV?",
            ". Does the Facility have fire protection equipment?",
            ".Fire etinguishers",
            ".Emergency eits",
            "Additional:",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the Facility have a written program for maintaining fire protection equipment ?",
            "Does the Facility have adequate security?",
            ".A larm system?",
            ". Burglar bars?",
            ". Lockable gates?",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the Facility have the following policies",
            "· supplies and purchasing",
            "· management of epired supplies",
            "Does the Facility have adequate supplies for services provided/",
            "Is there a stock control system?",
            "Amalgam hand instruments?",
            "Amalgam capsules?",
            "Cavity lining material",
            "Wedges",
            "Retention pins",
            "Matri holders/retainers",
            "Matri bands",
            "Articulating paper",
            "Polishing kits",
            "Hand pieces and burrs",
            "Composite filling with:",
            "Composite hand instruments",
            "Curing light",
            "Composite material",
            "Cavity liners",
            "Etching system",
            "Transparent strips",
            "Polishing kits and strips",
            "Hand pieces and burrs",
            "Root canal treatment with:--",
            "Endodontic kit with files and reamers",
            "Gutta Percha points",
            "Paper points",
            "Endo ruler",
            "Canal medicaments",
            "Root canal hand instruments",
            "Scaling with:--",
            "Scaling hand instruments",
            "Ultrasonic scaler",
            "Polishing brushes and cups",
            "Disclosing tablets",
            "Polishing paste",
            "Mouth wash tablets",
            "Oral surgery pack with:",
            "Tooth etraction forceps",
            "BP knife",
            "Surgical blades",
            "Scissors",
            "Needle holders",
            "Artery forceps",
            "Root elevators",
            "Periosteal elevators",
            "Retractors (tissue, cheek",
            "Suture material",
            "General items in treatment room:",
            "Non sterile gloves",
            "Surgical masks",
            "Dental needles",
            "Dental syringes",
            "Local anaesthetic solution",
            "Gauze",
            "Disinfectant",
            "-ray viewer",
            "An emergency kit ?",
        ]
    },
    "TENS": {
        "showOnly": [
            "Customer satisfaction--",
            "Is there a customer feedback mechanism",
            "Suggestion bo",
            "Customer surveys",
            "Is there a patient charter in both English and Setswana",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
        ]
    },
    "HIV SCREENING": {
        "showOnly": [
            "Instrument washing/sterilising room--",
            "Is there a washing room with adequate space?",
            "Is the room equipped with the following",
            "-Stainless steel sink with running water",
            "-Stainless steel waste discarding sink supplied with hot and cold water",
            "Is the room ventilated? Elaborate",
            "Is the room equipped with the following--",
            "· Chair",
            "· Microwave",
            "· Autoclave",
            "· Sterilising containers",
            "· Sterilising solutions",
            "· Pack wrappers",
            "· Disinfectant",
            "· Sharps container",
            "· Waste bin with lid for clinical waste",
            "· Waste bin with lid for domestic waste",
            "· Hand wash facilities",
            "· Appropriate hand drying facilities",
            "· Disposable gloves",
        ]
    },

};

export default Dental;
