/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-09-21 23:13:46
 * Facility Type: Dental
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Dental = {
    "ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does The Facility Have An Organisational Structure",
            "Is The Director A Medically Trained Person?",
            "Does The Facility Have Statutory Requirements?--",
            "Work Permits For Staff",
            "Lease Agreement",
            "Business Registration",
            "Trade Licence",
            "Contracts For Staff",
            "Occupancy Certificate",
            "Letter Of Permission To Set Up/Operate",
            "Waste Collection Carrier Licence",
            "Police Clearance For Employees",
            "Confidentiality Clause",
            "Proof Of Change Of Land Use Fire Clearance",
            "Resident Permit",
            "Copies Of Statutory",
            "Indemnity Insuarance",
            "Copies Of Relevant Statutory Instruments E.G. Public Health Act 2013, Botswana Health Professions Act,2001",
            "Is There Indemnity Insurance?",
            "Does The Clinic Have Policies And Procedures For The Following?--",
            "Patient Consent",
            "Patients Referral",
            "Assessment Of Patients",
            "Testing And Treatment Techniques",
            "Management Of High Risk Patients",
            "Confidentiality Of Patient Information",
            "Incident Reporting",
            "Orientation And Induction",
            "Linen Management",
            "Equipment Maintenance Plan/Program",
            "Testing And Commissioning Certificates",
            "Treatment Protocols/Guidelines",
            "Incident Reporting",
            "Infection Prevention And Control",
            "Management Of Patient Records And Retention Times",
            "Management Of Information",
            "Risk Management",
            "Management Of Supplies",
            "Patient Observation",
            "Management Of Medication",
            "Post Exposure Prophylaxis",
            "Complaints Procedure",
            "Outreach Services",
            "Waste Management",
        ]
    },
    "SERVICE PROVIDED": {
        "showOnly": [
            "What Are The Services Provided At The Facility?--",
            "Specialists Services (Specify)",
            "General Consultations",
            "Dental Surgery",
            "Cosmetic Dentistry (Braces And Implants)",
            "Community Health Services (Preventive)",
            "Dental Whitening And Teeth Cleaning",
            "Fillings And Dentures",
            "Crowns And Bridges",
            "Root Canal Treatment",
            "Home Visits",
            "Others (Specify)",
            "Any Outreach Services? If Yes",
            "Is There Letter Of Permission To Offer The Outreach Services",
            "Is There Proof Of Agreement? Agreement Letter With The Facility Where Services Will Be Offered From",
            "Is There Provision Of Emergency Contact Numbers?",
            "Are The Service To Be Provided Displayed?",
            "Are Emergency Contact Numbers Displayed?",
            "What Is Number Of Patients Seen Per Month?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What Is The Intended Total Number Of Staff?",
            "What Is The Current Total Number Of Staff?",
            "How Many Will Be?--",
            "Dentist",
            "Dental Thereapist",
            "Dental Assistant",
            "Dental Technology",
            "Administrative",
            "Support Staff",
            "Other (Specify)",
            "Are Professionals Registered With The Relevant Councils?",
            "Personnel Files Have The Following? --",
            "Signed Job Effectiveness Description",
            "Education Credentials",
            "A Signed Confidentially Clause",
            "Evidence Of Orientation And Induction",
            "Evidence Of Continued Education",
            "Signed Contracts Or Offer Letters",
            "Medical Examination Certificates",
        ]
    },
    "ENVIRONMENT": {
        "showOnly": [
            "Does The Facility Have Wheelchair Accessibility Or Elevators?",
            "Where There Are Ramps, Are There Safety Features?",
            "Is It Fenced, Secure And Easily Accessible",
            "Is There Adequate Space For Parking?",
            "Is Facility Area Clean And Neat?",
            "Are Surfaces Free From Dust?",
            "Is There Adequate Lighting?",
            "Is Air Conditioning Available?",
            "Is There Enough Ventilation?",
            "Is Flooring Of Cleanable, Smooth Impervious Material?",
            "Are There Relevant Restriction Signs",
            "Is There Parking Space Designated For People Living With Disability?",
            "Is There Directional Signage Within And Outside The Facility?",
            "Is There Backup System For Electricity And Water?",
            "Is There Provision For Water Testing?",
        ]
    },
    "RECEPTION AREA": {
        "showOnly": [
            "Does Reception Area Have Adequate Space?",
            "Is The Telephone Or Cell Phone Available?",
            "Is A Reception Desk With Chair Available",
            "Is There A Computer?",
            "Is It Manned At All Times?",
            "Is There An Organized Patient Registration, Screening, And Booking System",
            "Are There Adequate Patient Benches / Chairs?",
            "Is There A Waste Bin With A Lid?",
            "Is There A Displayed Setswana And English Patient Charter?",
            "Is There Available Drinking Source?",
            "Is There Information Available On The Hazards Of Radiation In The Reception?",
            "Are Educational Materials Available For Clients?",
        ]
    },
    "SCREENING ROOM": {
        "showOnly": [
            "Does The Screening Room Have Adequate Space?",
            "Does The Screening Room Have Wheelchair Accessibility?",
            "Is The Screening Room Equipped With?--",
            "Chairs And Table",
            "Sphygmonometer (Adults & Paediatrics)",
            "Thermometer",
            "Glucometer And Strips",
            "Alcohol Swabs",
            "Weighing Scale",
            "Height Measuring Device",
            "Non Sterile Gloves",
            "Clinical Waste Bins With Lids",
            "Domestic Waste Bin With Lids",
            "Sharp Containers",
            "Hand Wash Facilities",
            "Appropriate Hand Drying Facilities",
        ]
    },
    "CONSULTATION ROOM": {
        "showOnly": [
            "Does The Consultation Room Have Adequate Space?",
            "Does The Consultation Room Have Wheelchair Accessibility?",
            "Does The Consultation Room Have The Following?--",
            "At Least 3 Chairs",
            "Sterile Gloves",
            "Thermometer",
            "Glucometer* And Strips",
            "Height Measuring Device*",
            "Non Sterile Gloves",
            "Clinical Waste Bins With Lids",
            "Domestic Waste Bin With Lids",
            "Sharps Container",
            "Appropriate Hand Washing Facilities",
            "Appropriate Hand Drying Facilities",
            "Disposable Cups",
            "Tongue Depressors",
            "X Ray Viewing Box*",
            "Reference Material",
            "Dental Chair Covered With Head Rest And All Attachment",
            "Dental Stools",
            "Storage Space For Dental Consumables",
            "Mouth Gargle",
        ]
    },
    "INSTRUMENT WASHING/ STERILISING ROOM": {
        "showOnly": [
            "Is There A Washing Room With Adequate Space?",
            "Is The Room Equipped With The Following--",
            "Stainless Steel Sink With Running Water",
            "Stainless Steel Waste Discarding Sink Supplied With Hot And Cold Water",
            "Does The Room Have Adequate Ventilation?",
            "Is The Room Equipped With The Following--",
            "Chair",
            "Microwave",
            "Autoclave",
            "Sterilising Containers",
            "Sterilising Solutions",
            "Pack Wrappers",
            "Disinfectant",
            "Sharps Container",
            "Waste Bin With Lid For Clinical Waste",
            "Waste Bin With Lid For Domestic Waste",
            "Hand Wash Facilities",
            "Appropriate Hand Drying Facilities",
            "Disposable Gloves",
            "0",
        ]
    },
    "TOILET FACILITITES": {
        "showOnly": [
            "Is There A Minimum Of Two Toilets Available (For Male And",
            "Female Patients)?",
            "Are They Labelled Ï¿½Maleï¿½ And Ï¿½Female?Ï¿½",
            "Are Toilets Fitted With Hand Wash Facilities?",
            "Is There Suitable Soap Dispenser?",
            "Is There An Appropriate Hand Drying Provision?",
            "Is There A Separate Toilet For Staff?",
            "Is There A Toilet That Is Designed For Wheel Chair Users?",
            "Are Toilets Wheel Chair Accessible?",
            "Does The Female Toilet Have Sanitary Pads Disposal?",
            "Are Toilets Aesthetically Pleasing?",
            "Is There Provision For Paediatric Clients?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does The Facility Have A Policy On Waste Management?",
            "Does The Clinic Have Sops On Waste Management?",
            "Does The Clinic Have A Waste Disposal System? Specify:--",
            "Domestic Waste",
            "Clinical Waste",
            "Other Waste",
            "Does The Clinic Have A Policy And Procedures On Safety?",
            "Is There A Process For Equipment Sterilisation?",
            "Is There A Policy And Procedure On Accidental Exposure To Hiv?",
            "Does The Clinic Have Fire Protection Equipment?--",
            "Fire Extinguishers",
            "Emergency Exits",
            "Additional:--",
            "Fire Alarms",
            "Smoke Detectors",
            "Fire Blankets",
            "Fire Hose Reel",
            "Does The Clinic Have A Written Program For Maintaining Fire Protection Equipment",
            "Fire Inspection Report?",
            "Does The Clinic Have Adequate Security?",
            "Alarm System?",
            "Burglar Bars?",
            "Lockable Gates?",
            "Others--",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does The Clinic Have The Following Policies--",
            "Supplies And Purchasing",
            "Management Of Expired Supplies",
            "Decontamination Sop",
            "Does The Clinic Have Adequate Supplies For Services Provided?",
            "Is There A Stock Control System? If Yes Explain",
            "Does The Clinic Have Equipment Maintenance Plan And Routine Service Plan",
            "Does The Clinic Have An Asset Register",
            "Surfaces Finished With An Impervious Washable Material",
            "Is Stock Arranged And Labelled In A Systematic Manner",
            "Are Supplies Well Protected From Direct Sunlight",
            "Is There A Lockable Refrigerator For The Storage Of Thermo-Labile Drugs With Temperature Monitoring For Fridges And Room Temperature",
        ]
    },
    "RECORDS/ INFORMATION MANAGEMENT": {
        "showOnly": [
            "Are Patients Records Well Maintained?",
            "Is There A Policy On Patient Confidentiality?",
            "Are Records Controlled And Safe From Manipulation?",
            "Are Records Kept Electronically?",
            "Is There A Backup System For Electronic Data?",
            "If Hard Copies Are Kept, Is There A System For Protection Against Damage?",
            "Is There A Policy On Record Retention Times?",
            "Are Hard Copies Kept In A Lockable Cabinet For Maximum Security?",
        ]
    },
    "CUSTOMER SATISFACTION": {
        "showOnly": [
            "Is There A Customer Feedback Mechanism--",
            "Suggestion Box",
            "Customer Surveys",
            "Others",
            "Is There Provision For Consent Before Carrying Out Any Procedures/Assessment",
            "Is There A Complaints, Procedure",
        ]
    },

};

export default Dental;
