/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist-final.csv
 * Generated on: 2026-01-18 15:31:01
 *
 * This file defines facility service departments based on actual sections
 * found in the CSV checklist configuration.
 * To regenerate this file, run: python src/config/generateFilters.py
 */

// All available facility service departments (sections from CSV)
export const ALL_FACILITY_DEPARTMENTS = [
  "SECTION A-ORGANISATION AND MANAGEMENT",
  "SERVICES PROVIDED",
  "PERSONNEL",
  "FACILITY-ENVIRONMENT",
  "FACILITY-RECEPTION/WAITING AREA",
  "FACILITY-SCREENING ROOM",
  "FACILITY-CONSULTATION/ TREATMENT ROOM",
  "NURSES' STATION",
  "IN PATIENT ADMISSION ROOMS",
  "OFFICE FOR THE MANAGER",
  "EMERGENCY EQUIPMENT",
  "FACILITY-PROCEDURE ROOM",
  "SLUICE ROOM",
  "BLEEDING ROOM",
  "TOILET FACILITIES",
  "PHARMACY/DISPENSARY",
  "SAFETY AND WASTE MANAGEMENT",
  "SUPPLIES",
  "TENS",
  "CUSTOMER SATISFACTION",
  "SPECIMEN RECEPTION ROOM",
  "LABORATORY TESTING AREAS CHEMISTRY",
  "HIV SCREENING",
  "INSTRUMENT WASHING/STERILISING ROOM",
  "X-RAY ROOM",
  "ULTRASOUND ROOM",
  "FACILITY-CALL CENTRE",
  "FACILITY GOVERNANCE AND MANAGEMENT",
  "RESUSCITATION SERVICES",
  "OUT PATIENT SERVICE",
  "OBSTETRICS AND GYNAECOLOGY",
  "CENTRAL SUPPLY / STERILIZATION",
  "PHARMACY",
  "RADIOLOGY (MEDICAL IMAGING; X?RAY DEPARTMENT)",
  "PHYSIOTHERAPY CARE",
  "ENGINEERING / MAINTENANCE SERVICES",
];

// Mapping of specializations to their available departments
export const SPECIALIZATION_DEPARTMENT_MAPPING = {
  "Obstetrics & Gynaecology": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "EMERGENCY EQUIPMENT",
    "FACILITY-PROCEDURE ROOM",
    "SLUICE ROOM",
    "BLEEDING ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Laboratory": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "FACILITY-PROCEDURE ROOM",
    "BLEEDING ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "SPECIMEN RECEPTION ROOM",
    "LABORATORY TESTING AREAS CHEMISTRY",
    "HIV SCREENING",
    "ULTRASOUND ROOM",
  ],

  "Psychology": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Eye (Opthalmology /Optometry)": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "EMERGENCY EQUIPMENT",
    "FACILITY-PROCEDURE ROOM",
    "SLUICE ROOM",
    "BLEEDING ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Physiotherapy": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Dental": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "INSTRUMENT WASHING/STERILISING ROOM",
    "ULTRASOUND ROOM",
  ],

  "Dental Laboratory": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Ear, Nose & Throat": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "EMERGENCY EQUIPMENT",
    "FACILITY-PROCEDURE ROOM",
    "SLUICE ROOM",
    "BLEEDING ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Rehabilitation Centre": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "NURSES' STATION",
    "IN PATIENT ADMISSION ROOMS",
    "OFFICE FOR THE MANAGER",
    "EMERGENCY EQUIPMENT",
    "FACILITY-PROCEDURE ROOM",
    "SLUICE ROOM",
    "BLEEDING ROOM",
    "TOILET FACILITIES",
    "PHARMACY/DISPENSARY",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Radiology": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "X-RAY ROOM",
    "ULTRASOUND ROOM",
  ],

  "General Practice": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "EMERGENCY EQUIPMENT",
    "FACILITY-PROCEDURE ROOM",
    "SLUICE ROOM",
    "BLEEDING ROOM",
    "TOILET FACILITIES",
    "PHARMACY/DISPENSARY",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Paediatric": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "EMERGENCY EQUIPMENT",
    "FACILITY-PROCEDURE ROOM",
    "SLUICE ROOM",
    "BLEEDING ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Nursing  Home": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "FACILITY-RECEPTION/WAITING AREA",
    "FACILITY-SCREENING ROOM",
    "FACILITY-CONSULTATION/ TREATMENT ROOM",
    "NURSES' STATION",
    "IN PATIENT ADMISSION ROOMS",
    "OFFICE FOR THE MANAGER",
    "EMERGENCY EQUIPMENT",
    "FACILITY-PROCEDURE ROOM",
    "SLUICE ROOM",
    "BLEEDING ROOM",
    "TOILET FACILITIES",
    "PHARMACY/DISPENSARY",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
  ],

  "Emergency Medical Services": [
    "SECTION A-ORGANISATION AND MANAGEMENT",
    "SERVICES PROVIDED",
    "PERSONNEL",
    "FACILITY-ENVIRONMENT",
    "OFFICE FOR THE MANAGER",
    "SLUICE ROOM",
    "TOILET FACILITIES",
    "SAFETY AND WASTE MANAGEMENT",
    "SUPPLIES",
    "CUSTOMER SATISFACTION",
    "ULTRASOUND ROOM",
    "FACILITY-CALL CENTRE",
  ],

  "Hospital": [
    "TOILET FACILITIES",
    "FACILITY GOVERNANCE AND MANAGEMENT",
    "RESUSCITATION SERVICES",
    "OUT PATIENT SERVICE",
    "OBSTETRICS AND GYNAECOLOGY",
    "CENTRAL SUPPLY / STERILIZATION",
    "PHARMACY",
    "RADIOLOGY (MEDICAL IMAGING; X?RAY DEPARTMENT)",
    "PHYSIOTHERAPY CARE",
    "ENGINEERING / MAINTENANCE SERVICES",
  ],

};

/**
 * Get departments available for a specific specialization
 * @param {string} specialization - The facility specialization
 * @returns {Array<string>} Array of department names
 */
export function getDepartmentsForSpecialization(specialization) {
  if (!specialization || !SPECIALIZATION_DEPARTMENT_MAPPING[specialization]) {
    return ALL_FACILITY_DEPARTMENTS;
  }
  return SPECIALIZATION_DEPARTMENT_MAPPING[specialization];
}

/**
 * Get statistics about departments for a specialization
 * @param {string} specialization - The facility specialization
 * @returns {Object} Statistics object with total and available counts
 */
export function getDepartmentStats(specialization) {
  const available = getDepartmentsForSpecialization(specialization);
  return {
    total: ALL_FACILITY_DEPARTMENTS.length,
    available: available.length,
    specialization: specialization
  };
}

export default {
  ALL_FACILITY_DEPARTMENTS,
  SPECIALIZATION_DEPARTMENT_MAPPING,
  getDepartmentsForSpecialization,
  getDepartmentStats
};
