/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-12-14 20:45:42
 *
 * This file defines facility service departments based on actual sections
 * found in the CSV checklist configuration.
 * To regenerate this file, run: python src/config/generateFilters.py
 */

// All available facility service departments (sections from CSV)
export const ALL_FACILITY_DEPARTMENTS = [
  'BLEEDING ROOM',
  'FACILITY-CONSULTATION/ TREATMENT ROOM',
  'FACILITY-ENVIRONMENT',
  'FACILITY-PROCEDURE ROOM',
  'FACILITY-RECEPTION/WAITING AREA',
  'FACILITY-SCREENING ROOM',
  'HIV SCREENING',
  'ORGANISATION AND MANAGEMENT',
  'PERSONNEL',
  'PHARMACY/DISPENSARY',
  'SAFETY AND WASTE MANAGEMENT',
  'SERVICES PROVIDED',
  'SLUICE ROOM',
  'SUPPLIES',
  'TENS',
  'TOILET FACILITIES',
];

// Mapping of specializations to their available departments
export const SPECIALIZATION_DEPARTMENT_MAPPING = {
  'Obstetrics & Gynaecology': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'laboratory': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA',
    'HIV SCREENING',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Psychology': [
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Eye (Opthalmology /Optometry)': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Physiotheraphy': [
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Dental': [
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'HIV SCREENING',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Dental Laboratory': [
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Ear, Nose & Throat': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Rehabilitation Centre': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Radiology': [
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA',
    'HIV SCREENING',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'General Practice': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'PHARMACY/DISPENSARY',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Paediatric': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

  'Nursing Home': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA',
    'FACILITY-SCREENING ROOM',
    'ORGANISATION AND MANAGEMENT',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
  ],

};

/**
 * Get departments available for a specific specialization
 * @param {string} specialization - The facility specialization
 * @returns {Array<string>} Array of department names
 */
export function getDepartmentsForSpecialization(specialization) {
  if (!specialization || !SPECIALIZATION_DEPARTMENT_MAPPING[specialization]) {
    return ALL_FACILITY_DEPARTMENTS;
  }
  return SPECIALIZATION_DEPARTMENT_MAPPING[specialization];
}

/**
 * Get statistics about departments for a specialization
 * @param {string} specialization - The facility specialization
 * @returns {Object} Statistics object with total and available counts
 */
export function getDepartmentStats(specialization) {
  const available = getDepartmentsForSpecialization(specialization);
  return {
    total: ALL_FACILITY_DEPARTMENTS.length,
    available: available.length,
    specialization: specialization
  };
}

export default {
  ALL_FACILITY_DEPARTMENTS,
  SPECIALIZATION_DEPARTMENT_MAPPING,
  getDepartmentsForSpecialization,
  getDepartmentStats
};
