/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist-final.csv
 * Generated on: 2026-01-21 07:01:09
 *
 * This file defines facility service departments based on actual sections
 * found in the CSV checklist configuration.
 * To regenerate this file, run: python src/config/generateFilters.py
 */

// All available facility service departments (sections from CSV)
export const ALL_FACILITY_DEPARTMENTS = [
  'ACCIDENT & EMERGENCY AND RESUSCITATION SERVICES',
  'ADMINISTRATIVE SERVICES',
  'BLEEDING ROOM',
  'CENTRAL SUPPLIES AND STERILISATION DEPARTMENT (CSSD)',
  'COMBINED GENERAL MEDICAL/ SURGICAL/PAEDIATRIC WARDS',
  'CRITICAL CARE UNIT (HIGH CARE)',
  'CUSTOMER CARE, RIGHTS AND SATISFACTION',
  'CUSTOMER SATISFACTION',
  'DENTAL',
  'DIETETICS',
  'EMERGENCY EQUIPMENT',
  'EQUIPMENT AND HEALTHCARE TECHNOLOGY',
  'EYE CLINIC',
  'FACILITY ENVIRONMENT',
  'FACILITY GOVERNANCE AND MANAGEMENT',
  'FACILITY RESUSCITATION SERVICES',
  'FACILITY-PROCEDURE ROOM',
  'FOOD SERVICE AND KITCHEN',
  'GENERAL MEDICAL WARDS',
  'HIV SCREENING',
  'HOSPITAL SUPPLIES',
  'HOUSEKEEPING SERVICE',
  'HUMAN RESOURCE MANAGEMENT',
  'IN PATIENT ADMISSION ROOMS',
  'INFECTION PREVENTION AND CONTROL',
  'INSTRUMENT WASHING/STERILISING ROOM',
  'LABORATORY',
  'LABORATORY TESTING AREAS CHEMISTRY',
  'LAUNDRY SERVICES',
  'MAINTENANCE SERVICES',
  'NURSES\' STATION',
  'OBSTETRICS AND GYNAECOLOGY',
  'OCCUPATIONAL THERAPY',
  'OFFICE FOR THE MANAGER',
  'OPERATING THEATRE',
  'OUT PATIENT SERVICE',
  'PAEDIATRIC CARE/ SPECIALTIES AND WARDS/ NEONATOLOGY',
  'PERSONNEL',
  'PHARMACY',
  'PHARMACY/DISPENSARY',
  'PHYSIOTHERAPY CARE',
  'PSYCHIATRIC SERVICES AND WARDS',
  'RADIOLOGY (MEDICAL IMAGING; X-RAY DEPARTMENT)',
  'SAFETY AND WASTE MANAGEMENT',
  'SECTION A-ORGANISATION AND MANAGEMENT',
  'SERVICES PROVIDED',
  'SLUICE ROOM',
  'SOCIAL WORK',
  'SPECIMEN RECEPTION ROOM',
  'SPEECH THERAPY',
  'SUPPLIES',
  'SURGICAL /ORTHOPAEDIC WARDS',
  'TENS',
  'TOILET FACILITIES',
  'ULTRASOUND ROOM',
  'X-RAY ROOM',
];

// Mapping of specializations to their available departments
export const SPECIALIZATION_DEPARTMENT_MAPPING = {
  'Obstetrics & Gynaecology': [
    'BLEEDING ROOM',
    'CUSTOMER SATISFACTION',
    'EMERGENCY EQUIPMENT',
    'FACILITY-PROCEDURE ROOM',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Laboratory': [
    'BLEEDING ROOM',
    'CUSTOMER SATISFACTION',
    'FACILITY-PROCEDURE ROOM',
    'HIV SCREENING',
    'LABORATORY TESTING AREAS CHEMISTRY',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SPECIMEN RECEPTION ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Psychology': [
    'CUSTOMER SATISFACTION',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Eye (Opthalmology /Optometry)': [
    'BLEEDING ROOM',
    'CUSTOMER SATISFACTION',
    'EMERGENCY EQUIPMENT',
    'FACILITY-PROCEDURE ROOM',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Physiotheraphy': [
    'CUSTOMER SATISFACTION',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Dental': [
    'CUSTOMER SATISFACTION',
    'INSTRUMENT WASHING/STERILISING ROOM',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Dental Laboratory': [
    'CUSTOMER SATISFACTION',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Ear, Nose & Throat': [
    'BLEEDING ROOM',
    'CUSTOMER SATISFACTION',
    'EMERGENCY EQUIPMENT',
    'FACILITY-PROCEDURE ROOM',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Rehabilitation Centre': [
    'BLEEDING ROOM',
    'CUSTOMER SATISFACTION',
    'EMERGENCY EQUIPMENT',
    'FACILITY-PROCEDURE ROOM',
    'IN PATIENT ADMISSION ROOMS',
    'NURSES\' STATION',
    'OFFICE FOR THE MANAGER',
    'PERSONNEL',
    'PHARMACY/DISPENSARY',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Radiology': [
    'CUSTOMER SATISFACTION',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
    'X-RAY ROOM',
  ],

  'General Practice': [
    'BLEEDING ROOM',
    'CUSTOMER SATISFACTION',
    'EMERGENCY EQUIPMENT',
    'FACILITY-PROCEDURE ROOM',
    'PERSONNEL',
    'PHARMACY/DISPENSARY',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Paediatric': [
    'BLEEDING ROOM',
    'CUSTOMER SATISFACTION',
    'EMERGENCY EQUIPMENT',
    'FACILITY-PROCEDURE ROOM',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Nursing  Home': [
    'BLEEDING ROOM',
    'CUSTOMER SATISFACTION',
    'EMERGENCY EQUIPMENT',
    'FACILITY-PROCEDURE ROOM',
    'IN PATIENT ADMISSION ROOMS',
    'NURSES\' STATION',
    'OFFICE FOR THE MANAGER',
    'PERSONNEL',
    'PHARMACY/DISPENSARY',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Emergency Medical Services': [
    'CUSTOMER SATISFACTION',
    'OFFICE FOR THE MANAGER',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Hospital': [
    'ACCIDENT & EMERGENCY AND RESUSCITATION SERVICES',
    'ADMINISTRATIVE SERVICES',
    'CENTRAL SUPPLIES AND STERILISATION DEPARTMENT (CSSD)',
    'COMBINED GENERAL MEDICAL/ SURGICAL/PAEDIATRIC WARDS',
    'CRITICAL CARE UNIT (HIGH CARE)',
    'CUSTOMER CARE, RIGHTS AND SATISFACTION',
    'DENTAL',
    'DIETETICS',
    'EQUIPMENT AND HEALTHCARE TECHNOLOGY',
    'EYE CLINIC',
    'FACILITY ENVIRONMENT',
    'FACILITY GOVERNANCE AND MANAGEMENT',
    'FACILITY RESUSCITATION SERVICES',
    'FOOD SERVICE AND KITCHEN',
    'GENERAL MEDICAL WARDS',
    'HOSPITAL SUPPLIES',
    'HOUSEKEEPING SERVICE',
    'HUMAN RESOURCE MANAGEMENT',
    'INFECTION PREVENTION AND CONTROL',
    'LABORATORY',
    'LAUNDRY SERVICES',
    'MAINTENANCE SERVICES',
    'OBSTETRICS AND GYNAECOLOGY',
    'OCCUPATIONAL THERAPY',
    'OPERATING THEATRE',
    'OUT PATIENT SERVICE',
    'PAEDIATRIC CARE/ SPECIALTIES AND WARDS/ NEONATOLOGY',
    'PHARMACY',
    'PHYSIOTHERAPY CARE',
    'PSYCHIATRIC SERVICES AND WARDS',
    'RADIOLOGY (MEDICAL IMAGING; X-RAY DEPARTMENT)',
    'SAFETY AND WASTE MANAGEMENT',
    'SOCIAL WORK',
    'SPEECH THERAPY',
    'SURGICAL /ORTHOPAEDIC WARDS',
  ],

};

/**
 * Get departments available for a specific specialization
 * @param {string} specialization - The facility specialization
 * @returns {Array<string>} Array of department names
 */
export function getDepartmentsForSpecialization(specialization) {
  if (!specialization || !SPECIALIZATION_DEPARTMENT_MAPPING[specialization]) {
    return ALL_FACILITY_DEPARTMENTS;
  }
  return SPECIALIZATION_DEPARTMENT_MAPPING[specialization];
}

/**
 * Get statistics about departments for a specialization
 * @param {string} specialization - The facility specialization
 * @returns {Object} Statistics object with total and available counts
 */
export function getDepartmentStats(specialization) {
  const available = getDepartmentsForSpecialization(specialization);
  return {
    total: ALL_FACILITY_DEPARTMENTS.length,
    available: available.length,
    specialization: specialization
  };
}

export default {
  ALL_FACILITY_DEPARTMENTS,
  SPECIALIZATION_DEPARTMENT_MAPPING,
  getDepartmentsForSpecialization,
  getDepartmentStats
};
