// src/config/facilityServiceFilters/gynaeClinics.js
const gynaeClinics = {
    'ORGANISATION AND MANAGEMENT: Inspection': {
        showOnly: [
      'Does the clinic have an organisational structure',
      'Is the director a medically trained person',
      'Does the facility have statutory requirements?',
      'Business registration',
      'Work permits',
      'Lease agreement',
      'Trading license',
      'Permission to operate/set up',
      'Occupancy certificate',
      'Patient charter in English & Setswana',
      'Copies of relevant statutory instruments e.g. Public Health Act 2013, Botswana Health Professions Act,2001',
      'Is there an indemnity insurance',
      'Have personnel been cleared by police',
      'contracts for staff',
      'letter of permission to set up/operate',
      'waste collection carrier licence',
      'police clearance for employees',
      'confidentiality clause',
      'proof of change of land use',
      'tax clearance certificate',
      'Practitioner’s licence',
      'Fire clearance',
      'work permits',
      'residence permit',
      'contracts for staff',
      'Is there an indemnity insurance'
        ]
    },
    'SECTION B-STATUTORY REQUIREMENTS': {
        showOnly: [
      'Does the facility have statutory requirements?',
      'Business registration',
      'Work permits',
      'Lease agreement',
      'Trading license',
      'Permission to operate/set up',
      'Occupancy certificate',
      'Patient charter in English & Setswana',
      'Copies of relevant statutory instruments e.g. Public Health Act 2013, Botswana Health Professions Act,2001',
      'Is there an indemnity insurance',
      'Have personnel been cleared by police',
      'contracts for staff',
      'letter of permission to set up/operate',
      'waste collection carrier licence',
      'police clearance for employees',
      'confidentiality clause',
      'proof of change of land use',
      'tax clearance certificate',
      'Practitioners licence',
      'Fire clearance',
      'work permits',
      'residence permit',
      'contracts for staff'
    ]
  },
  'SECTION C-POLICIES AND PROCEDURES': {
    showOnly: [
      'Does the clinic have policies and procedures for the following?',
      'referral systems',
      'assessment of patients',
      'treatment protocols',
      'testing and treatment techniques',
      'high risk patients and procedures, and',
      'the confidentiality of patient information',
      'incident reporting',
      'Induction and orientation',
      'patient consent',
      'Linen management',
      'Equipment maintenance plan/program',
      'Testing and commissioning certificates',
      'Infection prevention and control',
      'Management of patient records and retention times',
      'Management of information ',
      'Risk management ',
      'Management of supplies',
      'Patient observation',
      'Management of medication',
      'Post exposure prophylaxis',
      'Complaints procedure',
      'Outreach services',
      'Waste management'
    ]
  },
  'SERVICES PROVIDED: Inspection': {
    showOnly: [
      'What are the services provided at the clinic?',
      'Gynaecology services',
      'Fertility',
      'Sexual reproductive health',
      'Antenatal care',
      'Post-natal care',
      'Post-abortal care',
      'Lab-Specialist services (specify)',
      'Lab-Laboratory services(specify)',
      'Lab-Specimen collection (specify)',
      'Eye- Vision services',
      'Eye -Medical eye care',
      'Eye- Surgical eye care',
      'Eye- Diagnosis & treatment of eye conditions',
      'Eye- Plastic surgery',
      'General Practice',
      'Specialist services (specify)',
      'General practice',
      'Specialist services',
      'Home visits',
      'Others ',
      'General consultations',
      'Hearing & balance services',
      'Voice, speech & swallowing',
      'Allergy, sinuses & sleep disorders',
      'Medical examinations ',
      'Dental surgery',
      'Cosmetic dentistry (braces and implants)',
      'Community health services (Preventive)',
      'Dental whitening and teeth cleaning',
      'Fillings and  dentures ',
      'Root canal treatment',
      'Crowns and bridges',
      'Addiction treatment (Alcohol and drug addiction, Gambling addiction, Sex addiction, Mood addiction, Gaming addiction)',
      'Mental health/ dual diagnosis treatment (Anxiety, Depression, Trauma, Sexual disorders, Mood disorders, Psychosis, Psychosocial such as misconduct, missing school, missing work and malingering )',
      'Chronic pain management (For individuals who have been on prolonged medication use, includes medication adherence)',
      'Psychometric assessment (For the disorders mentioned above and others)',
      'Pharmaceutical services (specify)',
      'Education credentials',
      'A signed confidentiality clause',
      'Evidence of orientation and induction',
      'Evidence of continuous professional development(CPD)',
      'What are the hours of operation',
      'Is there a services board within the facility',
      'What is number of patients seen per month',
      'Any outreach services? If yes',
      'Is there permission to offer the outreach services',
      'Agreement letter with a doctor where services will be offered from',
      'Is there provision of emergency contact numbers? '
    ]
  },
  'PERSONNEL: Inspection': {
    showOnly: [
      'What is the intended total number of staff',
      'What is the current number of staff',
      'How many will be ',
      'Gynaecologists ',
      'Medical Doctors',
      'Other specialist doctors',
      'Nurses',
      'Pharmacists',
      'Pharmacy technicians',
      'Administrative staff',
      'Support staff',
      'Other professionals (specify)',
      'Specialist doctors',
      'Laboratory scientists',
      'Laboratory technicians',
      'Psychologist',
      'Medical Doctors',
      'Nurses',
      'Ophthalmologists',
      'Optometrists',
      'Opticians',
      'Physiotherapists',
      'Physiotherapy assistants',
      'Dentist',
      'Dental therapist',
      'Dental assistant',
      'Dental technologist',
      'ENT specialist',
      'Psychologists',
      'Social workers',
      'Kitchen staff',
      'Pharmacy technicians',
      'Laboratory scientists',
      'Laboratory technicians',
      'Radiographers',
      'Radiologists',
      'Sonographers',
      'Radiology technicians ',
      'Are professionals registered with the relevant Councils',
      'Did personnel files have',
      'Signed job effectiveness description',
      'Education credentials',
      'A signed confidentiality clause',
      'Evidence of orientation and induction',
      'Evidence of continued education',
      'Signed contracts or offer letters',
      'Medical examination certificates'
    ]
  },
  'FACILITY: Environment Inspection': {
    showOnly: [
      'Does the facility have wheelchair accessibility',
      'Is it fenced, secure and easily accessible',
      'Is there adequate space for parking',
      'Is facility area clean and neat',
      'Are surfaces free from dust',
      'Is there adequate lighting',
      'Is air conditioning available',
      'Is there enough ventilation',
      'Is flooring of cleanable, smooth impervious material?',
      'Are there relevant restriction signs',
      'Is there parking space designated for people living with disability',
      'Is there directional signage within and outside the facility',
      'Is there backup system for electricity and water',
      'Where there are ramps, are there safety features?'
    ]
  },
  'FACILITY: Reception/waiting area Inspection': {
    showOnly: [
      'Does reception area have adequate space',
      'Is the telephone/ cell phone available',
      'Is a reception desk with chair available',
      'Is it manned at all times',
      'Is there an organized patient registration, screening and booking system',
      'Are there adequate patient benches / chairs in the waiting area',
      'Is there a waste bin',
      'Is there a computer',
      'Is there patient charter available in Setswana and English',
      'Is there available drinking water source',
      'Are educational materials available for clients'
    ]
  },
  'FACILITY: Screening Room Inspection': {
    showOnly: [
      'Does the screening room have adequate space',
      'Does the screening room have wheelchair accessibility',
      'Is screening room equipped with?',
      'Chairs and table',
      'Sphygmomanometer',
      'Thermometer',
      'Glucometer and strips',
      'Alcohol Swabs',
      'Weighing scale (both adult and paediatric)',
      'Height measuring device',
      'Non sterile gloves',
      'Waste bins with lids for clinical waste',
      'Waste bin with lids for domestic waste',
      'Sharps container',
      'Hand wash facilities',
      'Appropriate hand drying facilities'
    ]
  },
  'FACILITY: Consultation Room Inspection': {
    showOnly: [
      'Does the consultation room have adequate space',
      'Does the consultation room have wheelchair accessibility',
      'Does the consultation room have the following',
      'At least 3 Chairs ',
      'Alcohol swabs',
      'Appropriate hand drying facilities',
      'Appropriate soap dispenser',
      'Audiometer',
      'Autoclave',
      'Autorefrator',
      'Binocular indirect ophthalmoscope',
      'Bead bath heater',
      'Cabinet/Storage space',
      'clinical waste bin with lid',
      'Condoms',
      'Cone and thudichum speculum (nasal and ear speculum)',
      'Cotton swabs soaked in alcohol',
      'Cotton wool/wipes',
      'Curette',
      'dental chair covered with head rest and all attachment',
      'Dental stools',
      'Diagnostic set*',
      'Direct ophthalmoscope',
      'disposable cups',
      'Disposable gloves',
      'domestic waste bin with lids for ',
      'Drip stand',
      'Ear microscope',
      'Emergency tray*',
      'Endoscope and endoscopic light',
      'Examination chair',
      'Examination couch with tiltable headrest, covered with linen',
      'Examination gynaecological bed/couch with straps, covered with linen',
      'Examination lamp*',
      'Examination/treatment couch behind a curtain or located within a screened off alcove to provide privacy',
      'Examination/treatment couch covered with clean linen',
      'Examination/treatment couch with tiltable head rest',
      'Fetoscope',
      'Foetal monitor',
      'Forceps',
      'Glucometer* and strips',
      'Hand wash facilities',
      'Head light / head mirror ',
      'Height measuring device',
      'HIV testing kit',
      'Irrigator ',
      'Is the couch behind a curtain or located within a screened off alcove to provide privacy',
      'Jobson-Horne’s probe',
      'Laryngoscope',
      'Lensometer',
      'Lubricating jell or solution',
      'Manual keratometer',
      'Mouth gargle',
      'Needle holders',
      'Non sterile gloves',
      'Otoscope set',
      'Pap smear test kit (brush, fixator, frosted microscope glass slides)',
      'Patellar hammer',
      'Pen torch*',
      'Pre chopper',
      'Reference material*',
      'Retinal camera',
      'Sanitary pads',
      'Sharps container',
      'Siegel’s speculum',
      'Slit lamp',
      'Snellen  chart (6 meters from client)',
      'Sound proof room/ booth',
      'Spectacles',
      'Speculum',
      'Sphygmomanometer*',
      'Step stool to ease access to couch',
      'Sterile gloves',
      'Stool*',
      'Storage space for dental consumables*',
      'Suction apparatus*',
      'Tape measure',
      'Thermometer*',
      'Tissues',
      'Tongue depressors*',
      'Tonometer',
      'Toric marker',
      'Tuning fork*',
      'Ultra sound jelly',
      'Ultra sound machine*',
      'Vaginal speculae (different sizes)',
      'Waste bin with lids for domestic waste',
      'Waste bins with lids for clinical waste',
      'Weighing scale (both adult and paediatric)*',
      'X-ray viewing box'
        ]
    },
    'FACILITY: Procedure Room Inspection': {
        showOnly: [
      'Does the procedure room have adequate space?',
      'Is the room wheelchair accessible',
      'Does the procedure room have the following',
      'Alcohol swabs',
      'Antiseptic ointments, creams, solutions etc.',
      'Appropriate hand drying facilities',
      'Autoclave',
      'bandages and plasters ',
      'Chairs ',
      'clinical waste bins with lid ',
      'Cotton swabs soaked in alcohol',
      'Cupboards and suitably surfaced bench tops',
      'Curette',
      'Dilatation and curettage set ',
      'Disinfectants or antiseptic solutions',
      'domestic waste bin with lid ',
      'Drip stand',
      'Examination Chair ',
      'Examination couch with tiltable headrest, covered with linen',
      'Examination lamp*',
      'Glucometer* and strips',
      'Gynaecological  couch with straps',
      'Hand wash facilities',
      'Irrigator ',
      'Is the couch behind a curtain or located within a screened off alcove to provide privacy',
      'Lockable refrigerator for injectable with temperature monitoring device',
      'Lubricating jell or solution',
      'Nebulizing machine and solutions',
      'Needles (different sizes)',
      'Non sterile gloves',
      'Normal saline',
      'Pap smear set',
      'Pregnancy test kit',
      'Sanitary pads',
      'Sharps container',
      'Sphygmomanometer*(both adult and paediatric)*',
      'Stainless steel sink',
      'Steps to ease access to couch',
      'Sterile dressing packs (sponge forceps, toothed and non-toothed forceps, straight artery forceps, 2 galley pots, sterile gauge and cotton wool swabs, kidney dish, scalpel)',
      'Sterile gloves',
      'Sterile suture pack (gale pots, needle holder, scalpel, pair of stich scissors, tooth forceps)',
      'Sutures',
      'Tongue depressors*',
      'Tracheostomy set',
      'Urinary catheters (different sizes)',
      'Vaginal speculae (different sizes)',
      'Waste bin with lids for domestic waste',
      'Waste bins with lids for clinical waste'
    ]
  },
  'FACILITY: Sluice Room Inspection': {
    showOnly: [
      'Is the room equipped with the following',
      'Canvas bag trolley with cover',
      'Canvas bag trolley with cover for non soiled linen',
      'Canvas bag trolley with cover for soiled linen',
      'Clinical waste bins with lid',
      'Disinfectant',
      'Domestic waste bins with lid',
      'Heavy duty gloves',
      'Non sterile gloves',
      'Stainless steel sink with running water'
    ]
  },
  'FACILITY: Bleeding Room Inspection': {
    showOnly: [
      'Is the room equipped with the following',
      '2 chairs',
      'Blood tubes of different colours',
      'Needles and syringes (different sizes)',
      'Vacutainer',
      'Tourniquet',
      'Plaster',
      'Cotton swab',
      'Disinfectant',
      'Sharps container',
      'Clinical waste  bin with lid ',
      'Domestic waste bin with lid ',
      'Hand wash facilities',
      'Appropriate hand drying facilities',
      'Disposable gloves',
      'Cooler box',
      'Ice packs',
      'Specimen racks'
    ]
  },
  'FACILITY: Inspection of Toilet Facilities': {
    showOnly: [
      'Is there a minimum of two toilets available (for male and ',
      'Female patients)',
      'Are they labelled male and female?',
      'Are toilets fitted with hand wash facilities',
      'Is there suitable soap dispenser',
      'Is there an appropriate hand drying provision',
      'Is there a separate toilet for staff',
      'Is there a toilet that is designed for wheel chair users',
      'Are toilets wheel chair accessible',
      'Does the female toilet have sanitary pads disposal',
      'Are toilets aesthetically pleasing',
      'Is there provision for paediatric clients'
    ]
  },
  'FACILITY: Pharmacy/Dispensary Inspection': {
    showOnly: [
      'Is there a pharmacy personnel employed to carry out the pharmacy functions',
      'Does the dispensary have adequate space to allow for an efficient workflow',
      'Are  there adequate shelves for stock keeping',
      'Is stock arranged and labelled in a systematic manner',
      'Are drugs well protected from direct sunlight',
      'Are all surfaces finished with an impervious washable material',
      'Are all surfaces in a good state of repair',
      'is there a lockable refrigerator for the storage of thermos-labile drugs',
      'Are there mechanisms in place for monitoring and controlling room temperatures (storage and dispensary)',
      'Are there mechanisms in place for monitoring and controlling  refrigerator temperatures',
      'Is the sink supplied with hot and cold water',
      'Are the floors, walls, ceiling and shelves kept satisfactorily clean',
      'Is there a suitable lighting in the dispensary',
      'Is there a suitable means for counting tablets and capsules dispensed',
      'Is there a suitable means of measuring liquids dispensed',
      'Is the preparation room clean as per the requirements',
      'Are there suitable ranges of containers for the dispensing of:',
      'Tablets/capsules',
      'Liquids',
      'Cream/ointments',
      'Are there suitable labels for the above mentioned',
      'Is there a register for drugs of schedule 1A, 1B and 1C',
      'Is there a lockable cabinet for the storage of 1A and 1B drugs?',
      'Is there a policy for the management of expired drugs?',
      'Is there adequate security in the dispensary?',
      'Is there a stock management system?'
    ]
  },
  'FACILITY: Inspection of Safety and Waste Management': {
    showOnly: [
      'Does the clinic have a policy on waste management',
      'Does the clinic have SOPs on waste management',
      'Does the clinic have a waste disposal system? Specify:',
      'Domestic Waste',
      'Clinical Waste',
      'Does the clinic have a policy and procedures on safety',
      'Is there a policy and procedure on accidental exposure to HIV',
      'Does the clinic have fire protection equipment',
      'Fire extinguishers ',
      'Emergency exits',
      'Additional:',
      'Fire alarms',
      'Smoke detectors',
      'Fire blankets',
      'Fire Hose',
      'Does the clinic have a written program for maintaining fire ',
      'Protection equipment',
      'Fire inspection report',
      'Does the clinic have adequate security',
      'Alarm system',
      'Burglar bars',
      'Lockable gates'
    ]
  },
  'FACILITY: Supplies Inspection': {
    showOnly: [
      'Does the clinic have the following policies ',
      'supplies and purchasing',
      'management of expired supplies',
      'Does the clinic have adequate supplies for services provided',
      'Is there a stock control system? '
    ]
  },
  'FACILITY: Records/Information Management Inspection': {
    showOnly: [
      'Are patients records well maintained',
      'Is there a policy on patient confidentiality',
      'Are records controlled and safe from manipulation ',
      'Are records kept electronically',
      'Is there a backup system for electronic data',
      'If hard copies are kept, is there a system for protection against damage',
      'Is there a policy on record retention times',
      'Are hard copies kept in a lockable cabinet for maximum security'
    ]
  },
  'FACILITY: Customer Satisfaction Inspection': {
    showOnly: [
      'Is there a customer feedback mechanism',
      'Suggestion box',
      'Customer surveys',
      'Is there a patient charter in both English and Setswana',
      'Is there provision for consent before carrying out any procedures/assessment',
      'Is there a complaints, procedure'
    ]
  },
  'SPECIMEN RECEPTION ROOM: Inspection': {
    showOnly: [
      'Does the room have the following:',
      'Chairs and a table',
      'Disposable gloves',
      'Specimen racks and trays',
      'Specimen register/computer',
      'Markers/stickers',
      'Sharps container',
      'Waste bin with lid for clinical waste',
      'Waste bin with lid for domestic waste',
      'Is there an organised specimen registration system?',
      'Does registration use a unique patient identification',
      'Is there identification kept throughout lab testing',
      'Is there provision for patient privacy?',
      'Is there documented specimen acceptance/rejection criteria',
      'Does the lab have a documented specimen system( collection, handling, storage and transportation',
      'Is there specimen fridge with temperature monitoring device and chart',
      'Is there air-conditioner with monitoring device and chart?'
    ]
  },
  'LABORATORY TESTING AREAS CHEMISTRY: Inspection': {
    showOnly: [
      'Chemistry',
      'Does the testing area have adequate space?',
      'Are there adequate lab stools and benches?',
      'Is there hand washing provision?',
      'Is there air-conditioner with monitoring device and chart?',
      'List the clinical chemistry tests done by the lab:',
      'Does the lab have Technical SOPs (test methods)',
      'Does the lab have the following equipment:',
      'Chemistry analyser',
      'Centrifuge',
      'Medical fridge',
      'Medical freezer',
      'Graduated Pipettes',
      'Automated Pipettes',
      'Water distiller or provision for distilled water',
      'Are normal and abnormal Quality Control done and recorded',
      'How often are Quality controls run?',
      'Are QC results monitored over a period of time?',
      'Does the lab participate in External Quality Assessment Schemes?',
      'Are EQA results reviewed and monitored?',
      'Does the lab have Reference Ranges for the tests performed?',
      'Are refrigerator and freezer temperatures monitored?',
      'Waste bin with lid for clinical waste',
      'Waste bin with lid for domestic waste',
      'Are reagents stored appropriately? Explain',
      'Are lab equipment calibrated',
      'Is there an equipment preventative maintenance plan?',
      'Is expiry of items monitored?'
    ]
  },
  'LABORATORY TESTING AREAS HAEMATOLOGY: Inspection': {
    showOnly: [
      'Does the testing area have adequate space?',
      'Are there adequate lab stools and benches?',
      'Is there hand washing provision?',
      'Is there air-conditioner with monitoring device and chart?',
      'List clinical tests done at Haematology:',
      'Haematology:',
      'Does the testing area have adequate space?',
      'Are there adequate lab stools and benches?',
      'Is there hand washing provision?',
      'Is there air-conditioner with monitoring device and chart?',
      'List clinical tests done at Haematology:',
      'Does the lab have Technical SOPs (test methods)',
      'Does the lab have the following equipment?',
      'Haematology analyser?',
      'Microscope?',
      'Staining Racks?',
      'Water bath?',
      'Coagulation machine?',
      'ESR tubes and caps?',
      'Sample Rocker?',
      'Medical fridge?',
      'Sample rotator?',
      'Automated Pipettes?',
      'Graduated Pipettes?',
      'Pipette Fillers?',
      'Are normal and abnormal Quality Control done and recorded?',
      'How often are Quality controls run?',
      'Are QC results monitored over a period of time?',
      'Does the lab participate in External Quality Assessment Schemes?',
      'Are EQA results reviewed and monitored?',
      'Does the lab have Reference Ranges for the tests performed?',
      'Are refrigerator and freezer temperatures monitored?',
      'Waste bin with lid for clinical waste',
      'Waste bin with lid for domestic waste',
      'Are reagents stored appropriately? Explain',
      'Are lab equipment calibrated',
      'Is there an equipment preventative maintenance plan?',
      'Is expiry of items monitored?'
    ]
  },
  'MICROBIOLOGY: Inspection': {
    showOnly: [
      'Does the testing area have adequate space?',
      'Are there adequate lab stools and benches?',
      'Is there hand washing provision?',
      'Is there air-conditioner with monitoring device and chart?',
      'List clinical tests done at microbiology:',
      'Does the lab have Technical SOPs (test methods)',
      'Does the lab have the following equipment:',
      'Incubators(CO2,O2,42OC)',
      'Microscopes?',
      'Autoclave?',
      'Anaerobic Jars?',
      'Wire loops',
      'Disposable Inoculating loops and needles?',
      'Urine wire loop',
      'Reading lamp',
      'Centrifuge?',
      'Vortex',
      'Staining racks?',
      'Sample rocker?',
      'Medical fridge',
      'Medical freezer?',
      'Hot plate?',
      'Weighing scale?',
      'Bunsen burner?',
      'Gas cylinders',
      'Autoclave',
      'Timers',
      'Reagent bottles(brown)',
      'Measuring Cylinders',
      'Conical flasks',
      'Reagent Preparation Bottles',
      'Universal Bottles',
      'Bijou bottles',
      'Graduated Pipettes',
      'Storage cabinet for flammables',
      'Urine centrifuge tubes',
      'Ready to use culture media',
      'Ready to use staining reagents',
      'Graduated Pipettes',
      'Does the lab have Quality Control Organisms?',
      'How often are QC run?',
      'Are QC results monitored over a period of time',
      'Does the lab participate in EQA Assessment Schemes?',
      'Are EQA results reviewed and  monitored',
      'Are refrigerator temperatures monitored',
      'HIV SCREENING',
      'Does the lab do any HIV screening'
    ]
  },
  'INSTRUMENT WASHING/STERILISING ROOM: Inspection': {
    showOnly: [
      'Is there a washing room with adequate space? ',
      'Is the  room equipped with the following',
      'Stainless steel sink with running water',
      'Stainless steel waste discarding sink supplied with hot and cold water',
      'Does the room have adequate ventilation?',
      'Is the room equipped with the following',
      'Chair',
      'Microwave',
      'Autoclave',
      'Sterilising containers',
      'Sterilising solutions',
      'Pack wrappers',
      'Disinfectant',
      'Sharps container',
      'Waste bin with lid for clinical waste',
      'Waste bin with lid for domestic waste',
      'Hand wash facilities',
      'Appropriate hand drying facilities',
      'Disposable gloves'
    ]
  }
};

export default gynaeClinics;