/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist-final.csv
 * Generated on: 2026-01-18 15:31:00
 * Facility Type: Hospital
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Hospital = {
    "FACILITY GOVERNANCE AND MANAGEMENT": {
        "showOnly": [
            "GOVERNANCE--",
            "1.1.1 Government",
            "1.1.2 Teaching",
            "1.1.3 Private",
            "1.1.3.1 Single proprietorship",
            "1.1.3.2 Partnership",
            "1.1.3.3 Corporation",
            "1.1.3.4 Civic organisation",
            "1.1.3.5 Religious/Mission",
            "1.1.3.6 Foundation",
            "1.1.4 Others, please specify",
            "ORGANIZATIONAL GOVERNANCE--",
            "1.2.1 Governing body present?",
            "1.2.2 Responsibilities documented?",
            "1.2.3 Governance structure exists?",
            "1.2.4 Structure known to staff?",
            "1.2.5 Approvals documented?",
            "1.2.6 BoardManagement relationship documented?",
            "1.2.7 Budget approval role known?",
            "1.2.8 Committees: Performance Improvement",
            "1.2.8 Committees: Quality Improvement",
            "1.2.8 Committees: Infection Prevention & Control",
            "1.2.8 Committees: Safety, Health & Environment",
            "1.2.8 Committees: Waste Management",
            "1.2.8 Committees: Drugs/Therapeutic/Blood Transfusion",
            "1.2.8 Committees: Medical & Surgical Equipment",
            "1.2.8 Committees: Building & Plant Maintenance",
            "1.2.8 Committees: Customer Complaints Handling",
            "1.2.8 Committees: Disciplinary",
            "1.2.8 Committees: Maternal Mortality Review",
            "1.2.8 Committees: Theatre Users",
            "1.2.8 Committees: Ethics",
            "1.2.8 Committees: Clinical Audit",
            "1.2.8 Committees: Resuscitation",
            "QUALITY MANAGEMENT--",
            "1.3.1.1 Quality Management System?",
            "1.3.1.3 Quality Improvement Committee?",
            "1.3.1.5 Quality manager in post?",
            "1.3.1.7 Strategic foundations (Mission/Vision/Values)?",
            "1.3.1.8 Mission statement clear?",
            "1.3.1.9 Coordination between director & staff?",
            "1.3.1.10 Coordination between departments?",
            "1.3.1.11 Quality improvement committee exists?",
            "INFORMATION TECHNOLOGY--",
            "1.3.2.1 Qualified IT manager?",
            "1.3.2.2 Documented IT structure?",
            "1.3.2.5 Professionals properly qualified?",
            "1.3.2.6 Staff trained in basic computer skills?",
            "1.3.2.7 Documented IT policies/procedures?",
            "1.3.2.8 Patient information system?",
            "1.3.2.9 IT equipment maintenance programme?",
            "1.3.2.10 Sufficient computers?",
            "1.3.2.10.1 Internet access?",
            "1.3.2.10.2 UPS available?",
            "1.3.2.11 Computers safe from unauthorized manipulation?",
            "1.3.2.12 Secure storage & backup?",
            "FACILITY MANAGEMENT--",
            "1.4.1 Documented organizational structure?",
            "1.4.2 Required competencies present?",
            "1.4.3 All positions filled?",
            "1.4.4 Employment plan exists?",
            "1.4.5 Senior manager responsible for operations?",
            "1.4.5.1 Senior manager qualified?",
            "1.4.5.2 Senior manager trained health professional?",
            "1.4.5.3 Superintendent assures compliance?",
            "1.5.1 Strategic plan exists?",
            "1.5.2 Business/corporate plan exists?",
            "1.5.3 Community leaders included in planning?",
            "1.5.4 Services consistent with mission?",
            "1.6.1 Managers for all departments?",
            "1.6.2 Managers qualified/trained?",
            "1.6.3 Job descriptions for managers?",
            "1.6.4 Managers involved in yearly planning?",
            "1.6.5 Policies available to staff?",
            "1.6.6 Policies implemented/monitored?",
            "POLICIES AND PROCEDURES--",
            "1.7.1 Policies to guide services?",
            "1.7.2 Policies disseminated to staff?",
            "1.7.3 Policies conform to laws/regulations?",
            "1.7.4 Access to care based on payment ability?",
            "1.7.5 Policies guiding clinical departments?",
            "1.7.6.1 Policies address staff knowledge/skills?",
            "1.7.6.2 Policies address required staff numbers?",
            "1.7.6.3 Policies address quality improvement programs?",
            "1.7.6.4 Policies address coordination with other departments?",
            "1.7.7 Policies implemented/monitored hospital-wide?",
            "1.7.8.1 Admission policies?",
            "1.7.8.2 Discharge policies?",
            "1.7.8.3 Referral policies?",
            "1.7.8.4 Confidentiality policies?",
            "1.7.8.5 Medical records policies?",
            "1.7.8.6 Waste management policies?",
            "1.7.8.7 Drug supply policies?",
            "1.7.8.8 Deaths policies?",
            "1.7.8.9 Disaster management policies?",
            "1.7.8.10 Patient care policies?",
            "1.7.8.11 Treatment protocols?",
            "1.7.8.12 Infection prevention & control policies?",
            "1.7.8.13 Special needs patients policies?",
        ]
    },
    "RESUSCITATION SERVICES": {
        "showOnly": [
            "RESUSCITATION--",
            "9.9.1 Does the unit have resuscitation room?",
            "9.9.2 Adequately equipped to handle emergencies?",
            "9.9.3 Is there an emergency trolley?",
            "9.9.4 Emergency trolley checklist available?",
            "9.9.5 Medicines/equipment/supplies available per checklist?",
            "9.9.6 Total number of staff trained on resuscitation",
            "9.9.7 Breakdown: nurses/doctors/admin/support/others",
            "9.9.8 Levels of resuscitation training exist?",
            "9.9.9 Education strategy to keep staff updated?",
            "9.9.10 New employees trained within 1 month?",
            "9.9.11 Staff with patient contact trained in BLS?",
            "9.9.12 Competency tests in resuscitation techniques?",
            "9.9.13 Updated list of equipment per area?",
            "9.9.14 Qualified person responsible for equipment checks?",
            "9.9.15 Records available to committee?",
            "9.9.16 Policies regulating best practice?",
            "9.9.17 Essential equipment checked daily?",
        ]
    },
    "OUT PATIENT SERVICE": {
        "showOnly": [
            "RECEPTION AREA--",
            "10.1.1 Adequate space?",
            "10.1.2 Telephone available?",
            "10.1.3 Reception desk with chair?",
            "10.1.4 Reception manned at all times?",
            "10.1.5 Organized patient registration system?",
            "10.1.6 Adequate benches/chairs?",
            "10.1.7 Waste bin available?",
            "SCREENING ROOM--",
            "10.2.1 Adequate space?",
            "10.2.2 Wheelchair accessible?",
            "10.2.3 Equipped with chairs/table?",
            "10.2.3.2 Sphygmomanometer?",
            "10.2.3.3 Thermometer?",
            "10.2.3.4 Glucometer?",
            "10.2.3.5 Cotton swabs (70% alcohol)?",
            "10.2.3.6 Weighing scale (adult/infant)?",
            "10.2.3.7 Height measuring device?",
            "10.2.3.8 Gloves sterile/non-sterile?",
            "10.2.3.10 Waste bin (clinical)?",
            "10.2.3.11 Waste bin (non-clinical)?",
            "10.2.3.12 Sharps container?",
        ]
    },
    "OBSTETRICS AND GYNAECOLOGY": {
        "showOnly": [
            "ORGANIZATION AND MANAGEMENT--",
            "16.1.1 Documented organizational structure?",
            "16.1.2 Documented policies and procedures?",
            "16.1.3 Equipment maintenance program?",
            "16.1.4 Quality Management System?",
            "16.1.5 Medical director for specialist wards?",
            "16.1.6 Nursing care supervised by qualified person?",
            "16.1.7 Unit in charge suitably qualified?",
            "16.1.8 Adequate equipment for services?",
            "16.1.9 Protocols for management of conditions?",
            "16.1.10 Segregation of patients per protocols?",
            "16.1.11 Policies/procedures for admission criteria?",
            "16.1.12 Orientation and in?service program for staff?",
            "PERSONNEL--",
            "16.2.1 Total number of staff?",
            "16.2.2 Breakdown: Medical Officers, Midwives, Nurses, Auxiliaries, Cleaners, etc.",
            "16.2.3 Professionals registered with Councils?",
            "NURSES STATION--",
            "16.3.1 Adequate space?",
            "16.3.2 Telephone/computer/printer available?",
            "16.3.3 Reception desk with chair?",
            "16.3.4 Manned at all times?",
            "16.3.5 Nurse call system with bed view panel?",
            "16.3.6 Waste bin available?",
            "CUBICLE--",
            "16.4.1 Adequate space?",
            "16.4.2 Wheelchair accessibility?",
            "16.4.3.1 Patient bed with tiltable headrest?",
            "16.4.3.2 Bed behind curtain/private alcove?",
            "16.4.3.3 Adequate patient lockers?",
            "16.4.3.4 Adequate cardiac tables?",
            "16.4.3.5 Washbasin with soap dispenser?",
            "16.4.3.6 Appropriate hand drying provision?",
            "16.4.3.7 Waste bin (clinical)?",
            "16.4.3.8 Waste bin (non?clinical)?",
            "PROCEDURE ROOM--",
            "16.5.1 Adequate space?",
            "16.5.2 Wheelchair accessible?",
            "16.5.3.1 Cupboards/bench tops?",
            "16.5.3.2 Chairs (with backrest)?",
            "16.5.3.3 Examination couch with linen?",
            "16.5.3.4 Couch behind curtain/private alcove?",
            "16.5.3.5 Steps for couch access?",
            "16.5.3.6 Examination lamp?",
            "16.5.3.7 Sphygmomanometer?",
            "16.5.3.8 Drip stand?",
            "16.5.3.9 Disposable gloves (sterile)?",
            "16.5.3.10 Disposable gloves (non?sterile)?",
            "16.5.3.11 Basin with running water/soap dispenser?",
            "16.5.3.12 Appropriate hand drying provision?",
            "16.5.3.13 Sharps container?",
            "16.5.3.14 X?ray viewing box?",
            "16.5.3.15 Resuscitation trolley regularly checked?",
            "DELIVERY ROOM--",
            "16.6.1 Adequate space?",
            "16.6.2 Wheelchair accessible?",
            "16.6.3.1 Adjustable delivery bed with linen?",
            "16.6.3.2 Bed behind curtain/private alcove?",
            "16.6.3.3 Steps for couch access?",
            "16.6.3.4 Examination lamp?",
            "16.6.3.5 Sphygmomanometer/Cardiac monitor?",
            "16.6.3.6 Drip stand?",
            "16.6.3.7 Disposable gloves (sterile)?",
            "16.6.3.8 Disposable gloves (non?sterile)?",
            "16.6.3.9 Basin with running water/soap dispenser?",
            "16.6.3.10 Appropriate hand drying provision?",
            "16.6.3.11 Sharps container?",
            "16.6.3.12 Oxygen with flow meters/masks?",
            "16.6.3.13 Suction machine/apparatus?",
            "16.6.3.14 Fetoscope/Foetal monitor?",
            "16.6.3.15 Wall clock?",
            "16.6.3.16 Post?partum haemorrhage emergency pack checked?",
            "16.6.3.17 Resuscitation trolley regularly checked?",
        ]
    },
    "CENTRAL SUPPLY / STERILIZATION": {
        "showOnly": [
            "STERILIZATION AREA--",
            "19.3.2.4 Linen packaging area with good ventilation?",
            "19.3.2.5 Loading and off?loading trays available?",
            "19.3.2.6 Sterilizers/autoclaves with approved controls/safety features?",
            "19.3.2.6 Sterilizers inspected/maintained per manufacturer recommendations?",
            "19.3.2.7 Method for checking sterilizer accuracy (chemical indicators)?",
            "19.3.2.8 Biological monitoring weekly?",
            "19.3.2.9 Storage separated into sterile/non?sterile areas?",
            "19.3.2.10 Storage area has temperature/humidity controls?",
            "19.3.2.11 Storage area free of moisture/dust?",
            "19.3.2.12 Countertops/tables disinfected each shift?",
            "19.3.2.13 Apparel laundered per hospital policy?",
            "19.3.2.14 Access to dirty corridor?",
            "19.3.2.15 CSSD has policies/procedures?",
            "STERILE STORE--",
            "19.4.1 Mechanism for monitoring temperature/humidity?",
            "19.4.2 Shelves fenestrated?",
            "19.4.3 Different instrument sets/drapes per specialty?",
            "19.4.4 Sterile gown sets available?",
            "19.4.5 Sterile gauze packs available?",
            "CHANGING ROOMS--",
            "19.5.1 Arranged to avoid exposure to dirty areas?",
            "19.5.2 Shelves for scrubs/clogs/overshoes/head caps?",
            "19.5.3 Male/female toilets with showers?",
            "19.5.4 Lockable cupboards for personal belongings?",
            "19.5.5 Toilets fitted with basins, soap, drying facilities?",
            "19.5.6 Female toilet has SHE bin with pedal?",
            "19.5.7 Changing room aesthetically pleasing?",
            "SUPPLIES--",
            "19.6.1 Policy on supplies/purchasing?",
            "19.6.2 Adequate supplies available?",
            "19.6.3 Policy on expired supplies?",
            "19.6.4 Stock control system?",
            "TOILET FACILITIES--",
            "19.7.1 Minimum two toilets (male/female)?",
            "19.7.2 Toilet suitable for children?",
            "19.7.3 Toilets labelled male/female?",
            "19.7.4 Toilets fitted with washbasin (hot/cold water)?",
            "19.7.5 Suitable soap dispenser?",
            "19.7.6 Appropriate hand drying provision?",
            "19.7.7 Separate toilet for staff?",
            "19.7.8 Toilet designed for wheelchair users?",
            "19.7.9 Female toilet has sanitary pad disposal?",
            "19.7.10 Toilets aesthetically pleasing?",
            "SAFETY AND WASTE MANAGEMENT--",
            "19.8.1 Policy on waste management?",
            "19.8.2 Standard operating procedures on waste management?",
            "19.8.3 Waste disposal system?",
            "19.8.4 Policy/procedures on safety?",
            "19.8.5 Fire protection equipment available?",
            "19.8.5.1 Fire extinguishers?",
            "19.8.5.2 Smoke detectors?",
            "19.8.5.3 Fire alarms?",
            "19.8.5.5 Fire blankets?",
            "19.8.5.6 Fire hose?",
            "19.8.6 Adequate security?",
            "19.8.6.1 Lockable gates?",
            "19.8.6.2 Lockable doors?",
            "19.8.6.3 Alarm system?",
            "19.8.6.4 Burglar bars?",
            "19.8.6.5 Security personnel?",
        ]
    },
    "PHARMACY": {
        "showOnly": [
            "ORGANIZATION AND MANAGEMENT--",
            "20.1.1 Director is trained health personnel?",
            "20.1.2 Documented organizational structure?",
            "20.1.3 Documented policies/procedures for pharmacy operations?",
            "20.1.4 Head/manager trained health personnel?",
            "20.1.5 Continuous supervision by registered pharmacist?",
            "20.1.6 Pharmacist registered with Botswana Health Professions Council?",
            "20.1.7 Registration updated this year?",
            "20.1.8 Registration certificate displayed?",
            "20.1.9 Pharmacist involved in other operations?",
            "20.1.20 Pharmacy inspected by BoMRA?",
            "20.1.21 Pharmacy appropriately licensed?",
            "20.1.22 License displayed?",
            "20.1.23 Pharmacists name/contact displayed at entrance?",
            "20.1.24 Quality Management System?",
        ]
    },
    "RADIOLOGY (MEDICAL IMAGING; X?RAY DEPARTMENT)": {
        "showOnly": [
            "ORGANIZATION AND MANAGEMENT--",
            "22.1.1 Documented organizational structure?",
            "22.1.2 Director is trained health personnel?",
            "22.1.3 Head/manager trained health personnel?",
            "22.1.4 Documented policies/procedures for services?",
            "22.1.5 Quality Management System in place?",
            "SERVICES PROVIDED--",
            "22.2.1.1 General practice services provided?",
            "22.2.1.2 Specialist services provided?",
            "22.2.1.3 Other services provided?",
            "PERSONNEL--",
            "22.3.1 Total number of staff recorded?",
            "22.3.2 Total number of professional staff?",
            "22.3.4 Staff registered with relevant councils?",
            "22.3.5 Receptionist full time?",
            "22.3.6 Cleaner full time?",
            "SUPPLIES--",
            "22.4.1 Policy on supplies/purchasing?",
            "22.4.2 Adequate storage space for supplies?",
            "22.4.3 Adequate supplies for services?",
            "22.4.4 Policy on expired supplies?",
            "22.4.5 Stock control system in place?",
            "22.4.6 Adequate supply of sheets/towels stored appropriately?",
            "RECEPTION / WAITING AREA--",
            "22.5.1 Reception area has adequate space?",
            "22.5.2 Telephone available?",
            "22.5.3 Reception desk and chair available?",
            "22.5.4 Receptionist present at all times?",
            "22.5.5 Standardized patient registration system?",
            "22.5.6 Adequate patient waiting chairs/benches?",
            "22.5.7 Waste bin available?",
            "22.5.8 Education materials available?",
            "22.5.9 Water fountain available?",
            "X?RAY ROOM--",
            "22.6.1 Adequate space?",
            "22.6.2 Wheelchair accessible?",
            "22.6.4 Red warning light at entrance?",
            "22.6.5 Examination/treatment couch with headrest?",
            "22.6.6 Lead gowns available?",
            "22.6.7 Gonad protection available?",
            "22.6.7.1 Thyroid shields available?",
            "22.6.7.2 Control panel shielded with lead window?",
            "22.6.8 X?Ray viewing box available?",
            "22.6.9 Waste bins (clinical/non?clinical)?",
            "22.6.10 Sharps disposal container available?",
            "22.6.11 Walls barium plastered?",
            "22.6.12 Walls built from 30cm concrete/air gap?",
            "22.6.13 Doors lined with lead?",
            "22.6.13.1 Doors sliding type?",
            "22.6.13.2 Non?sliding doors have lead strips?",
            "ULTRASOUND ROOM--",
            "22.7.1 Ultrasound machine commissioned/records available?",
            "22.7.2 Change room for patients available?",
            "22.7.3 Room accessible for wheelchair users?",
            "22.7.4 Clinical/domestic waste bins available?",
            "22.7.5 Adequate ventilation and lighting?",
            "22.7.6 Provision for handwashing?",
            "TOILET FACILITIES--",
            "22.8.1 Minimum two toilets (male/female)?",
            "22.8.2 Toilet suitable for children?",
            "22.8.3 Toilets labelled male/female?",
            "SAFETY AND WASTE MANAGEMENT--",
            "24.14.1 Policy on waste management?",
            "24.14.2 SOPs on waste management?",
            "24.14.3 Functional laundry facility?",
            "24.14.4 Laundry managed within clinic?",
            "24.14.4.2 Laundry managed outside?",
            "24.14.4.3 Laundry contracted?",
            "24.14.5 Other (specify)",
            "24.14.6 Waste disposal system in place?",
            "24.14.6.1 Chemical waste managed?",
            "24.14.6.2 Clinical waste managed?",
            "24.14.6.3 Pharmaceutical waste managed?",
            "24.14.7 Policy/procedures on safety?",
            "24.14.8 Policy on accidental HIV/infectious exposure?",
            "24.14.9 Fire protection equipment available?",
            "24.14.9.1 Fire extinguishers?",
            "24.14.9.2 Emergency exits?",
            "24.14.9.3 Fire alarms?",
            "24.14.9.4 Smoke detectors?",
            "24.14.9.5 Fire blankets?",
            "24.14.9.6 Fire hose?",
            "24.14.10 Written program for maintaining fire equipment?",
            "24.14.11 Adequate security?",
            "24.14.11.1 Alarm system?",
            "24.14.11.2 Burglar bars?",
            "24.14.11.3 Lockable gates?",
            "24.14.12 Disaster preparedness policy?",
        ]
    },
    "PHYSIOTHERAPY CARE": {
        "showOnly": [
            "ORGANIZATION AND MANAGEMENT--",
            "25.1.1 Documented organizational structure?",
            "25.1.2 Director is trained health personnel?",
            "25.1.3 Head/manager trained health personnel?",
            "25.1.4 Documented policies/procedures for services?",
            "25.1.5 Quality Management System in place?",
            "SERVICES PROVIDED--",
            "25.2.1 General practice services provided?",
            "25.2.2 Specialist services provided?",
            "25.2.3 Home visits provided?",
            "25.2.4 Outreach services provided?",
            "25.2.5 Other services specified?",
            "PERSONNEL--",
            "25.3.1 Total number of staff recorded?",
            "25.3.2 Total number of professional staff?",
            "25.3.4 Staff registered with relevant councils?",
            "25.3.5 Receptionist full time?",
            "SUPPLIES--",
            "25.4.1 Policy on supplies/purchasing?",
            "25.4.2 Adequate storage space for supplies?",
            "25.4.3 Adequate supplies for services?",
            "25.4.4 Policy on expired supplies?",
            "25.4.5 Stock control system in place?",
            "25.4.6.1 Taping materials available?",
            "25.4.6.2 Strapping material available?",
            "25.4.6.3 Crepe bandage available?",
            "25.4.6.4 Compression stocking available?",
            "25.4.6.5 Tubi?grip available?",
            "25.4.6.6 Braces available?",
            "25.4.6.7 Supports available?",
            "25.4.6.8 Ambulatory frames (adult) available?",
            "25.4.6.9 Ambulatory frames (paediatric) available?",
            "25.4.6.10 Rolator frames (adult) available?",
            "25.4.6.11 Rolator frames (paediatric) available?",
            "25.4.6.12 Crutches (axillary) available?",
            "25.4.6.13 Crutches (elbow) available?",
            "25.4.6.14 Tripod available?",
            "25.4.6.15 Ultrasound gel available?",
            "25.4.6.16 Electric pads available?",
            "25.4.6.17 Disinfectant available?",
            "25.4.6.18 Antiseptic available?",
            "25.4.6.19 Massage oil/cream available?",
            "RECEPTION / WAITING AREA--",
            "25.5.1 Reception area has adequate space?",
            "25.5.2 Telephone available?",
            "25.5.3 Reception desk with chair available?",
            "25.5.4 Reception manned at all times?",
            "25.5.5 Standardized patient registration system?",
            "25.5.6 Adequate patient benches/chairs?",
            "25.5.7 Waste bin available?",
            "25.5.8 Water fountain available?",
            "25.5.9 Education materials available?",
            "CONSULTATION / TREATMENT ROOM--",
            "25.6.1 Adequate space?",
            "25.6.2 Wheelchair accessible?",
            "25.6.3.1 Chair for patient available?",
            "25.6.3.2 Examination/treatment couch with headrest?",
            "25.6.3.3 Couch covered with clean linen?",
            "25.6.3.4 Couch behind curtain/private alcove?",
            "25.6.3.5 Wash basin with hot/cold water?",
            "25.6.3.6 Soap dispenser available?",
            "25.6.3.7 Appropriate hand drying provision?",
            "25.6.3.8 Clinical waste bin available?",
            "25.6.3.9 Non?clinical waste bin available?",
            "25.6.3.10 Non?sterile gloves available?",
            "25.6.3.11 Cotton wool/wipes available?",
            "25.6.3.12 X?Ray viewing box available?",
            "25.6.3.13 Sharps disposal container available?",
            "TOILET FACILITIES--",
            "25.7.1 Minimum two toilets available?",
            "25.7.2 Toilets labelled male/female?",
            "25.7.3 Toilets fitted with washbasin (hot/cold water)?",
            "TOILET FACILITIES--",
            "25.7.1 Minimum two toilets available?",
            "25.7.2 Toilets labelled male/female?",
            "25.7.3 Toilets fitted with washbasin (hot/cold water)?",
            "25.7.4 Suitable soap dispenser available?",
            "25.7.5 Appropriate hand drying provision?",
            "25.7.6 Toilet designed for wheelchair users?",
            "25.7.7 Toilets wheelchair accessible?",
            "25.7.8 Female toilet has sanitary pad disposal bin?",
            "SAFETY AND WASTE MANAGEMENT--",
            "25.8.1 Waste disposal system in place?",
            "25.8.1.1 Chemical waste managed?",
            "25.8.1.2 Clinical waste managed?",
            "25.8.1.3 Domestic waste managed?",
            "25.8.2 Policy/procedures on safety?",
            "25.8.3 Infection control policy in place?",
            "25.8.4 Policy on accidental HIV exposure?",
            "25.8.5 Hand washing policy in place?",
            "25.8.6 Fire protection equipment available?",
            "25.8.6.1 Fire extinguishers?",
            "25.8.6.2 Emergency exits?",
            "25.8.6.3 Fire alarms?",
            "25.8.6.4 Smoke detectors?",
            "25.8.6.5 Fire blankets?",
            "25.8.6.6 Fire hose?",
            "25.8.6.7 Overhead fire sprinklers?",
            "25.8.7 Written program for maintaining fire equipment?",
            "25.8.8 Adequate security in place?",
            "25.8.8.1 Alarm system?",
            "25.8.8.2 Burglar bars?",
            "25.8.8.3 Lockable doors?",
            "25.8.8.4 Lockable gates?",
            "25.8.8.5 Security personnel?",
            "CUSTOMER SATISFACTION--",
            "25.9.1 Customer feedback mechanism in place?",
            "25.9.2 Suggestion box available?",
            "25.9.3 Customer survey conducted?",
            "EQUIPMENT--",
            "25.9.1 Appropriate equipment/instruments available?",
            "25.9.2 Policy on equipment/instrument maintenance?",
            "25.9.3.1 Wheelchair available?",
            "25.9.3.2 Ultrasound machine available?",
            "25.9.3.3 Electrotherapy machine available?",
            "25.9.3.4 Short Wave diathermy machine available?",
            "25.9.3.5 Wooden couch for diathermy machine available?",
            "25.9.3.6 Infra?red lamp available?",
            "25.9.3.7 Laser therapy machine available?",
            "25.9.3.8 Ultra?violet lamp available?",
            "25.9.3.9 Hydro collator/moist heat machine available?",
            "25.9.3.10 Exercise weights available?",
            "25.9.3.11 Exercise cycle ergo meter available?",
            "25.9.3.12 Parallel bars available?",
            "25.9.3.13 Sphygmomanometer available?",
            "25.9.3.14 Stethoscope available?",
            "25.9.3.15 Hot pack available?",
            "25.9.3.15 Measuring tape available?",
            "25.9.3.16 Set of goniometers available?",
            "25.9.3.17 Pair of scissors available?",
            "25.9.3.18 Cryotherapy equipment available?",
            "25.9.3.19 Wax therapy equipment available?",
            "25.9.3.20 Galvanism equipment available?",
            "25.9.3.21 Laser beam equipment available?",
            "25.9.3.22 Dodynamic current equipment available?",
            "25.9.3.23 TENS equipment available?",
            "25.9.3.24 Muscle/nerve stimulation equipment available?",
            "25.9.3.25 Interferential therapy equipment available?",
            "25.9.3.26 Ultrasound equipment available?",
            "25.9.3.27 Microwave currents equipment available?",
            "REFERENCES--",
            "25.10.1.1 Health Policy available?",
            "25.10.1.2 National policy on HIV exposure available?",
            "25.10.1.3 Public Health Act available?",
            "25.10.1.4 Standards of Physiotherapy Practice in Botswana available?",
        ]
    },
    "ENGINEERING / MAINTENANCE SERVICES": {
        "showOnly": [
            "PERSONNEL--",
            "31.2.1 Total number of staff recorded?",
            "31.2.2 Breakdown: Engineers, Technicians, Admin, Support, Others",
            "31.2.3 Professionals registered with relevant councils?",
            "RECEPTION / WAITING AREA--",
            "31.3.1 Reception area has adequate space?",
            "31.3.2 Telephone available?",
            "31.3.3 Reception desk with chair available?",
            "31.3.4 Reception manned at all times?",
            "31.3.5 Adequate patient benches/chairs?",
            "31.3.6 Waste bin available?",
            "MAINTENANCE SERVICES--",
            "31.4.1 Supervisor qualified by training/experience?",
            "31.4.2 Contracted services have signed agreements?",
            "31.4.3 On?site workshop available?",
            "31.4.4 Patient care equipment tested/calibrated per manufacturer specs?",
            "31.4.5 Testing frequency/calibration documentation available?",
            "SUPPLIES--",
            "31.5.1 Policy on supplies/purchasing?",
            "31.5.2 Adequate supplies for services?",
            "31.5.3 Policy on expired supplies?",
            "31.5.4 Stock control system in place?",
            "TOILET FACILITIES--",
            "31.6.1 Minimum two toilets available (male/female)?",
            "31.6.2 Toilet suitable for children?",
        ]
    },

};

export default Hospital;
