/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-12-15 11:55:24
 * Facility Type: laboratory
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const laboratory = {
    "ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?",
            "Business registration",
            "Tax clearance certificate",
            "Valid private pactice license",
            "Work permits",
            "Residence permit",
            "Lease agreement",
            "Occupancy certificate",
            "Trading license",
            "Patient charter in English & Setswana",
            "Is there an indemnity insurance?",
            "contracts for staff",
            "Police Clearance",
            "letter of permission to set up",
            "waste collection carrier licence",
            "confidentiality clause",
            "proof of change of land use",
            "Practitioners licence",
            "Fire clearance",
            "residence permit",
            "Does the Facility have policies and procedures for the following?--",
            "Patient referral",
            "Management of high risk patients",
            "The confidentiality of patient information",
            "Incident reporting",
            "Induction and orientation",
            "Patient consent",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "Infection prevention and control",
            "Management of patient records",
            "Record retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post eposure prophylais",
            "Complaints procedure",
            "Outreach services",
            "Waste management",
            "Does the Facility have the following reference materials?--",
            "Treatment protocols/ guidelines",
            "Testing and treatment techniques",
            "Copies of relevant statutory instruments",
        ]
    },
    "SERVICES PROVIDED": {
        "showOnly": [
            "What are the services provided at the Facility?--",
            "General services; Specify",
            "Specialist services; Specify",
            "Other services (Specify); .....",
            "Is there a services board within the facility?",
            "Are hours of operation displayed?",
            "State hours of operation",
            "Are emergency contact numbers displayed?",
            "What is number of patients seen/ Samples received per month",
            "Any outreach services? If yes state them.",
            "Is there permission to offer the outreach services",
            "Agreement letter with a doctor where outreach services will be offered from",
            "Is there provision of emergency outreach services?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff",
            "What is the current number of staff--",
            "General Health Professionals (Specify)",
            "Specialists (Specify)",
            "Other (Specify)",
            "Administrative Staff (Specify)",
            "Support staff (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentiality clause",
            "Evidence of orientation and induction",
            "Evidence of continued education",
            "Signed contracts or offer letters",
            "Medical eamination certificates",
            "Evidence of continous Professional Development",
        ]
    },
    "FACILITY-ENVIRONMENT": {
        "showOnly": [
            "Does the facility have wheelchair accessibility?",
            "Is it fenced, secure and easily accessible",
            "Is there space for parking? Specify",
            "Is there parking space designated for people living with disability? Specify",
            "Do the facility have space for services provided? Specify",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there lighting in all service areas?",
            "Is air conditioning available?",
            "Is there ventilation in all service area?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity?",
            "Is there backup system for water?",
            "Where there are ramps, are there safety features?",
        ]
    },
    "FACILITY-RECEPTION/WAITING AREA": {
        "showOnly": [
            "Does reception area have space? Elaborate.",
            "Is the telephone/ cell phone available?",
            "Is a reception desk with chair available",
            "Is it manned at all times?",
            "Is there an organized patient registration, screening and booking system",
            "Are there patient benches / chairs in the waiting area? Elaborate.",
            "Is there a waste bin?",
            "Is there a computer/ desktop?",
            "Is there patient charter available in Setswana and English?",
            "Is there available drinking water source?",
            "Are educational materials available for clients",
        ]
    },
    "FACILITY-CONSULTATION/ TREATMENT ROOM": {
        "showOnly": [
            "Hand washing soap",
            "hand drying facilities",
        ]
    },
    "FACILITY-PROCEDURE ROOM": {
        "showOnly": [
            "Pregnancy test kit",
        ]
    },
    "BLEEDING ROOM": {
        "showOnly": [
            "Does the bleeding room have space? Elaborate.",
            "Does the room have wheelchair accessibility?",
            "Is the room equipped with the following --",
            "2 chairs",
            "Needles and syringes (different sizes)",
            "Vacutainers of different colours",
            "Tourniquet",
            "Plaster",
            "Cotton swab",
            "Disinfectant",
            "Sharps container",
            "Clinical waste bin with lid",
            "Domestic waste bin with lid",
            "Hand wash basin with running hot and cold water",
            "Hand wash soap",
            "Appropriate hand drying facilities",
            "Disposable gloves",
            "Cooler bo",
            "Ice packs",
            "Specimen racks",
        ]
    },
    "TOILET FACILITIES": {
        "showOnly": [
            "Is there a minimum of two toilets available (for male and",
            "Female patients)?",
            "Are they labelled male and female?",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Are toilets wheel chair accessible?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does the Facility have a policy on waste management?",
            "Does the Facility have SOPs on waste management?",
            "Does the Facility have a waste disposal system? Specify:",
            ". Domestic Waste",
            ". Clinical Waste",
            ". Does the Facility have a policy and procedures on safety?",
            ". Is there a policy and procedure on accidental eposure to HIV?",
            ". Does the Facility have fire protection equipment?",
            ".Fire etinguishers",
            ".Emergency eits",
            "Additional:",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the Facility have a written program for maintaining fire protection equipment ?",
            "Does the Facility have adequate security?",
            "A larm system?",
            "Burglar bars?",
            "Lockable gates?",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the Facility have the following policies--",
            "supplies and purchasing",
            "management of expired supplies",
            "Does the Facility have adequate supplies for services provided",
            "Is there a stock control system?",
        ]
    },
    "TENS": {
        "showOnly": [
            "Customer satisfaction--",
            "Is there a customer feedback mechanism",
            "Suggestion box",
            "Customer surveys",
            "Is there a patient charter in both English and Setswana",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
            "Specimen reception room--",
            "Does the room have the following:",
            "· Chairs and a table",
            "· Disposable gloves",
            "· Specimen racks and trays",
            ". Blood collection tubes, bottles, containers",
            "· Specimen register/computer",
            "· Markers/stickers",
            "· Sharps container",
            "· Waste bin with lid for clinical waste",
            "· Waste bin with lid for domestic waste",
            "· Is there an organised specimen registration system?",
            "· Does registration use a unique patient identification",
            "· Is there identification kept throughout lab testing",
            "· Is there provision for patient privacy?",
            "· Is there documented specimen acceptance/rejection criteria",
            "· Does the lab have a documented specimen system( collection, handling, storage and transportation",
            "· Is there specimen fridge with temperature monitoring device and chart",
            "Is there air-conditioner with monitoring device and chart?",
            "Laboratory testing areas Chemistry--",
            "Chemistry",
            "Does the testing area have adequate space?",
            "Are there adequate lab stools and benches?",
            "Is there hand washing provision?",
            "Is there air-conditioner with monitoring device and chart?",
            "List the clinical chemistry tests done by the lab:",
            "Does the lab have Technical SOPs (test methods)",
            "Does the lab have the following equipment: --",
            "· Chemistry analyser",
            "· Centrifuge",
            "· Medical fridge",
            "· Medical freezer",
            "· Graduated Pipettes",
            "· Automated Pipettes",
            "· Water distiller or provision for distilled water",
            "· Are normal and abnormal Quality Control done and recorded",
            "· How often are Quality controls run?",
            "· Are QC results monitored over a period of time?",
            "· Does the lab participate in Eternal Quality Assessment Schemes?",
            "· Are EQA results reviewed and monitored?",
            "· Does the lab have Reference Ranges for the tests performed?",
            "· Are refrigerator and freezer temperatures monitored?",
            "· Waste bin with lid for clinical waste",
            "· Waste bin with lid for domestic waste",
            "· Are reagents stored appropriately? Eplain",
            "· Are lab equipment calibrated",
            "· Is there an equipment preventative maintenance plan?",
            "· Is epiry of items monitored?",
            "Laboratory testing areas Haematology:--",
            "Does the testing area have adequate space?",
            "Are there adequate lab stools and benches?",
            "Is there hand washing provision?",
            "Is there air-conditioner with monitoring device and chart?",
            "List clinical tests done at Haematology:",
            "Haematology:",
            "Does the testing area have adequate space?",
            "Are there adequate lab stools and benches?",
            "Is there hand washing provision?",
            "Is there air-conditioner with monitoring device and chart?",
            "List clinical tests done at Haematology:",
            "Does the lab have Technical SOPs (test methods",
            "Does the lab have the following-- equipment? --",
            "· Haematology analyser?",
            "· Microscope?",
            "· Staining Racks?",
            "· Water bath?",
            "· Coagulation machine?",
            "· ESR tubes and caps?",
            "· Sample Rocker?",
            "· Medical fridge?",
            "· Sample rotator?",
            "· Automated Pipettes?",
            "· Graduated Pipettes?",
            "· Pipette Fillers?",
            "· Are normal and abnormal Quality Control done and recorded?",
            "· How often are Quality controls run?",
            "· Are QC results monitored over a period of time?",
            "· Does the lab participate in Eternal Quality Assessment Schemes?",
            "· Are EQA results reviewed and monitored?",
            "· Does the lab have Reference Ranges for the tests performed?",
            "· Are refrigerator and freezer temperatures monitored?",
            "· Waste bin with lid for clinical waste",
            "· Waste bin with lid for domestic waste",
            "· Are reagents stored appropriately? Eplain",
            "· Are lab equipment calibrated",
            "· Is there an equipment preventative maintenance plan?",
            "Is epiry of items monitored?",
            "Microbiology:--",
            "Does the testing area have adequate space?",
            "Are there adequate lab stools and benches?",
            "Is there hand washing provision?",
            "Is there air-conditioner with monitoring device and chart?",
            "List clinical tests done at microbiology:",
            "Does the lab have Technical SOPs (test methods",
            "Does the lab have the following equipment:--",
            "· Incubators(CO2,O2,42OC)",
            "· Microscopes?",
            "· Autoclave?",
            "· Anaerobic Jars?",
            "· Wire loops",
            "· Disposable Inoculating loops and needles?",
            "· Urine wire loop",
            "· Reading lamp",
            "· Centrifuge?",
            "· Vorte",
            "· Staining racks?",
            "· Sample rocker?",
            "· Medical fridge",
            "· Medical freezer?",
            "· Hot plate?",
            "· Weighing scale?",
            "· Bunsen burner?",
            "· Gas cylinders",
            "· Autoclave",
            "· Timers",
            "· Reagent bottles(brown)",
            "· Measuring Cylinders",
            "· Conical flasks",
            "· Reagent Preparation Bottles",
            "· Universal Bottles",
            "· Bijou bottles",
            "· Graduated Pipettes",
            "· Storage cabinet for flammables",
            "· Urine centrifuge tubes",
            "· Ready to use culture media",
            "· Ready to use staining reagents",
            "· Graduated Pipettes",
            "Does the lab have Quality Control Organisms?",
            "How often are QC run?",
            "Are QC results monitored over a period of time",
            "Does the lab participate in EQA Assessment Schemes?",
            "Are EQA results reviewed and monitored",
            "Are refrigerator temperatures monitored",
        ]
    },
    "HIV SCREENING": {
        "showOnly": [
            "Does the lab do any HIV screening",
        ]
    },

};

export default laboratory;
