/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-12-14 17:54:36
 * Facility Type: Nursing Home
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const NursingHome = {
    "ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?",
            "Does the facility comply with regulatory requirements? --",
            "Business registration",
            "Tax clearance certificate",
            "Valid private pactice license",
            "Work permits",
            "Residence permit",
            "Lease agreement",
            "Occupancy certificate",
            "Permission to operate/set up",
            "Patient charter in English & Setswana",
            "Is there an indemnity insurance?",
            "contracts for staff",
            "Police Clearance",
            "letter of permission to set up",
            "waste collection carrier licence",
            "confidentiality clause",
            "proof of change of land use",
            "Practitioners licence",
            "Fire clearance",
            "residence permit",
            "Does the Facility have policies and procedures for the following?--",
            "Patient referral",
            "Assessment of patients",
            "Management of high risk patients",
            "The confidentiality of patient information",
            "Incident reporting",
            "Induction and orientation",
            "Patient consent",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "Infection prevention and control",
            "Management of patient records",
            "Record retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post eposure prophylais",
            "Complaints procedure",
            "Outreach services",
            "Waste management",
            "Does the Facility have the following reference materials?--",
            "Treatment protocols/ guidelines",
            "Testing and treatment techniques",
            "Copies of relevant statutory instruments",
            "Treatment protocols/ guidelines",
            "Testing and treatment techniques",
            "Copies of relevant statutory instruments",
        ]
    },
    "SERVICES PROVIDED": {
        "showOnly": [
            "What are the services provided at the Facility?--",
            "General services; Specify",
            "Specialist services; Specify",
            "Other services (Specify); .....",
            "Is there a services board within the facility?",
            "Are hours of operation displayed?",
            "State hours of operation",
            "Are emergency contact numbers displayed?",
            "What is number of patients seen/ Samples received per month",
            "Any outreach services? If yes state them.",
            "Is there permission to offer the outreach services",
            "Agreement letter with a doctor where outreach services will be offered from",
            "Is there provision of emergency outreach services?",
            "Is there provision of emergency outreach services?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff",
            "What is the current number of staff--",
            "General Health Professionals (Specify)",
            "Specialists (Specify)",
            "Other (Specify)",
            "Administrative Staff (Specify)",
            "Support staff (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Did personnel files have the following?--",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentiality clause",
            "Evidence of orientation and induction",
            "Evidence of continued education",
            "Signed contracts or offer letters",
            "Medical eamination certificates",
            "Evidence of continous Professional Development",
            "Evidence of continous Professional Development",
        ]
    },
    "FACILITY-ENVIRONMENT": {
        "showOnly": [
            "Does the facility have wheelchair accessibility?",
            "Is it fenced, secure and easily accessible",
            "Is there space for parking? Specify",
            "Is there parking space designated for people living with disability? Specify",
            "Do the facility have space for services provided? Specify",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there lighting in all service areas?",
            "Is air conditioning available?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity?",
            "Is there backup system for water?",
            "Where there are ramps, are there safety features?",
        ]
    },
    "FACILITY-RECEPTION/WAITING AREA": {
        "showOnly": [
            "Does reception area have space? Elaborate.",
            "Is the telephone/ cell phone available?",
            "Is a reception desk with chair available",
            "Is it manned at all times?",
            "Is there an organized patient registration, screening and booking system",
            "Are there patient benches / chairs in the waiting area? Elaborate.",
            "Is there a waste bin?",
            "Is there a computer/ desktop?",
            "Is there patient charter available in Setswana and English?",
            "Is there available drinking water source?",
            "Are educational materials available for clients",
        ]
    },
    "FACILITY-SCREENING ROOM": {
        "showOnly": [
            "Does the screening room have space? Elaborate.",
            "Does the screening room have wheelchair accessibility?",
            "Is screening room equipped with the following?--",
            "Chairs and table",
            "Sphygmomanometer",
            "Thermometer",
            "Glucometer and strips",
            "Alcohol Swabs",
            "Weighing scale (both adult and paediatric)",
            "Height measuring device",
            "Non sterile gloves",
            "Clinical waste bin with lid",
            "Domestic waste bin with lid",
            "Sharps container",
            "Hand wash facilities",
            "Appropriate hand drying facilities",
            "Appropriate hand wash soap",
        ]
    },
    "FACILITY-CONSULTATION/ TREATMENT ROOM": {
        "showOnly": [
            "Does the consultation room have adequate space?",
            "Does the consultation room have wheelchair accessibility",
            "Does the consultation room have the following --",
            "At least 3 Chairs",
            "Alcohol swabs",
            "Appropriate hand drying facilities",
            "Appropriate soap dispenser",
            "Autoclave",
            "Cabinet/Storage space",
            "clinical waste bin with lid",
            "Cotton swabs soaked in alcohol",
            "Cotton wool/ wipes",
            "Diagnostic set*",
            "disposable cups",
            "Disposable gloves",
            "domestic waste bin with lid",
            "Drip stand",
            "Emergency tray",
            "Eamination/ treatment couch with tiltable headrest behind a curtain, covered with linen",
            "Eamination/ treatment couch behind a curtain or located within a screen off aclove to provide privacy?",
            "Eamination/ treatment couch covered with linen?",
            "Eamination lamp*",
            "Forceps",
            "Glucometer* and strips",
            "Hand washing basin with running hot and cold water",
            "Hand washing soap",
            "hand drying facilities",
            "Height measuring device",
            "HIV testing kit",
            "Laryngoscope set",
            "Lubricating jell or solution",
            "Needle holders",
            "Non sterile gloves",
            "Reference material",
            "Sharps container",
            "Sphygmomanometer*",
            "Step to ease access to couch",
            "Sterile gloves",
            "Storage space for consumables",
            "Suction apparatus",
            "Tape measure",
            "Thermometer*",
            "Tongue depressors",
            "Ultra sound jelly",
            "Waste bin with lids for domestic waste",
            "Waste bins with lids for clinical waste",
            "Weighing scale (both adult and paediatric)*",
            "X-ray viewing box",
            "Nurses' station--",
            "Desk",
            "Chairs",
            "Counter",
            "Computer with printer",
            "Nurse call system panel",
            "Telephone",
            "In patient Admission rooms--",
            "is the room wheelcahir accessible?",
            "are there separate male and female admission rooms?",
            "is there patient nurse call system in patient rooms and bathrooms?",
            "are the admission rooms labelled?",
            "Is there a bed with restaring accessories?",
            "Is linen available? ( sheets, bed cover, blankets, pillow, linen saver and mattress protector)",
            "Are bathroom facilities available with hot and cold running water ( bath tab/shower)?",
            "are the bathroom facilities accessible to whhel chair users?",
            "Is there a drying rail or rack?",
            "Is there hand washbasin with running hot and cold water?",
            "Is there hand wash soap?",
            "Is there hand drying facilities?",
            "is the SHE bin availble in the female bathrooms",
            "are there storage cabinets/ closets/ cupboards",
            "are there visitors/ pateints' chairs?",
            "Is there domestic waste bins with lid?",
            "Office for the Manager--",
            "Is there an office for the In- Charge officer?",
            "Does the oofice have the followig;",
            "Chairs?",
            "Table?",
            "Desktop/ computer connected to printer?",
            "Telephone?",
            "Habit Forming cabinet/ cupboard?",
            "Emergency equipment--",
            "emergency trolley with chelist with atleast",
            "Does the Emergency trolloey have atleast the following; Defibrilator/ Automated Eternal Difibrilator (AED), laryngoscope set, endotracheal tubes, ambu bags, syringes, needles, cannulas, alcohol swab, drugs, IV fluids, oygen cylinder and masks of different sizes, etc",
        ]
    },
    "FACILITY-PROCEDURE ROOM": {
        "showOnly": [
            "Does the procedure room have adequate space?",
            "Is the room wheelchair accessible",
            "Does the procedure room have the following --",
            "Alcohol swabs",
            "Antiseptic ointments, creams, solutions etc.",
            "Appropriate hand drying facilities",
            "Autoclave",
            "bandages and plasters",
            "Chairs",
            "clinical waste bins with lid",
            "Cotton swabs soaked in alcohol",
            "Cupboards and suitably surfaced bench tops",
            "Disinfectants or antiseptic solutions",
            "domestic waste bin with lid",
            "Drip stand",
            "Eamination couch with tiltable headrest, covered with linen",
            "Step to ease access to couch",
            "Eamination lamp*",
            "Glucometer* and strips",
            "Hand wash facilities",
            "handwash soap",
            "Is the couch behind a curtain or located within a screened off alcove to provide privacy",
            "Lockable refrigerator for medical supplies with temperature monitoring device",
            "Lubricating jell or solution",
            "Nebulizing machine and solutions",
            "Nebulizing machine and solutions",
            "Needles (different sizes)",
            "Non sterile gloves",
            "Normal saline",
            "Sharps container",
            "Sphygmomanometer*(both adult and paediatric)*",
            "Stainless steel sink",
            "Steps to ease access to couch",
            "Sterile dressing packs (sponge forceps, toothed and non-toothed forceps, straight artery forceps, 2 galley pots, sterile gauge and cotton wool swabs, kidney dish, scalpel)",
            "Sterile gloves",
            "Sterile suture pack (gallipots, needle holder, scalpel, pair of stich scissors, tooth forceps)",
            "Sutures",
            "Tongue depressors",
            "Tracheostomy set",
            "Urinary catheters (different sizes)",
            "Vaginal speculae (different sizes)",
            "Waste bin with lids for domestic waste",
            "Waste bins with lids for clinical waste",
        ]
    },
    "SLUICE ROOM": {
        "showOnly": [
            "Does the room have space? Elaborate.",
            "Does the room have ventilation? Elaborate",
            "Does the room have wheelchair accessibility?",
            "Is the room equipped with the following--",
            "Canvas bag trolley with cover",
            "Canvas bag trolley with cover for non soiled linen",
            "Canvas bag trolley with cover for soiled linen",
            "Clinical waste bins with lid",
            "Disinfectant",
            "Domestic waste bins with lid",
            "Heavy duty gloves",
            "Non sterile gloves",
            "Stainless steel sink with running water",
            "stainless steel waste discarding sink or sluice machine",
        ]
    },
    "BLEEDING ROOM": {
        "showOnly": [
            "Does the bleeding room have space? Elaborate.",
            "Does the room have wheelchair accessibility?",
            "Is the room equipped with the following --",
            "2 chairs",
            "Needles and syringes (different sizes)",
            "Vacutainers of different colours",
            "Tourniquet",
            "Plaster",
            "Cotton swab",
            "Disinfectant",
            "Sharps container",
            "Clinical waste bin with lid",
            "Domestic waste bin with lid",
            "Hand wash basin with running hot and cold water",
            "Hand wash soap",
            "Appropriate hand drying facilities",
            "Disposable gloves",
            "Cooler bo",
            "Ice packs",
            "Specimen racks",
        ]
    },
    "TOILET FACILITIES": {
        "showOnly": [
            "Is there a minimum of two toilets available (for male and",
            "Female patients)?",
            "Are they labelled male and female?",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Are toilets wheel chair accessible?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does the Facility have a policy on waste management?",
            "Does the Facility have SOPs on waste management?",
            "Does the Facility have a waste disposal system? Specify:",
            ". Domestic Waste",
            ". Clinical Waste",
            ". Does the Facility have a policy and procedures on safety?",
            ". Is there a policy and procedure on accidental eposure to HIV?",
            ". Does the Facility have fire protection equipment?",
            ".Fire etinguishers",
            ".Emergency eits",
            "Additional:",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the Facility have a written program for maintaining fire protection equipment ?",
            "Does the Facility have adequate security?",
            "A larm system?",
            "Burglar bars?",
            "Lockable gates?",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the Facility have the following policies--",
            "supplies and purchasing",
            "management of expired supplies",
            "Does the Facility have adequate supplies for services provided",
            "Is there a stock control system?",
        ]
    },
    "TENS": {
        "showOnly": [
            "Customer satisfaction--",
            "Is there a customer feedback mechanism",
            "Suggestion bo",
            "Customer surveys",
            "Is there a patient charter in both English and Setswana",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
            "Is there a complaints, procedure",
        ]
    },

};

export default NursingHome;
