/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist for facilities2.0.csv
 * Generated on: 2025-12-04 19:52:28
 * Facility Type: Psychology
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Psychology = {
    "ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?",
            "Business registration",
            "ta clearance certificate",
            "Valid private pactice license",
            "Work permits",
            "Residence permit",
            "Lease agreement",
            "Occupancy certificate",
            "Permission to operate/set up",
            "Patient charter in English & Setswana",
            "Is there an indemnity insurance?",
            "contracts for staff",
            "Police Clearance",
            "letter of permission to set up",
            "waste collection carrier licence",
            "confidentiality clause",
            "proof of change of land use",
            "Practitioners licence",
            "Fire clearance",
            "residence permit",
            "Patient referral",
            "Assessment of patients",
            "Management of high risk patients",
            "The confidentiality of patient information",
            "Incident reporting",
            "Induction and orientation",
            "Patient consent",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "Infection prevention and control",
            "Management of patient records",
            "Record retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post eposure prophylais",
            "Complaints procedure",
            "Outreach services",
            "Waste management",
            "Treatment protocols/ guidelines",
            "Testing and treatment techniques",
            "Copies of relevant statutory instruments",
        ]
    },
    "SERVICES PROVIDED": {
        "showOnly": [
            "General services; Specify",
            "Specialist services; Specify",
            "Other services (Specify); .....",
            "Is there a services board within the facility?",
            "Are hours of operation displayed?",
            "State hours of operation",
            "Are emergency contact numbers displayed?",
            "What is number of patients seen/ Samples received per month",
            "Any outreach services? If yes state them.",
            "Is there permission to offer the outreach services",
            "Agreement letter with a doctor where outreach services will be offered from",
            "Is there provision of emergency outreach services?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff",
            "What is the current number of staff--",
            "General Health Professionals (Specify)",
            "Specialists (Specify)",
            "Other (Specify)",
            "Administrative Staff (Specify)",
            "Support staff (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentiality clause",
            "Evidence of orientation and induction",
            "Evidence of continued education",
            "Signed contracts or offer letters",
            "Medical eamination certificates",
            "Evidence of continous Professional Development",
        ]
    },
    "FACILITY-ENVIONMENT": {
        "showOnly": [
            "Does the facility have wheelchair accessibility?",
            "Is it fenced, secure and easily accessible",
            "Is there space for parking? Specify",
            "Is there parking space designated for people living with disability? Specify",
            "Do the facility have space for services provided? Specify",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there lighting in all service areas?",
            "Is air conditioning available?",
            "Is there ventilation in all service area?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity?",
            "Is there backup system for water?",
            "Where there are ramps, are there safety features?",
        ]
    },
    "FACILITY-RECEPTION/WAITING AREA": {
        "showOnly": [
            "Does reception area have space? Elaborate.",
            "Is the telephone/ cell phone available?",
            "Is a reception desk with chair available",
            "Is it manned at all times?",
            "Is there an organized patient registration, screening and booking system",
            "Are there patient benches / chairs in the waiting area? Elaborate.",
            "Is there a waste bin?",
            "Is there a computer/ desktop?",
            "Is there patient charter available in Setswana and English?",
            "Is there available drinking water source?",
            "Are educational materials available for clients",
        ]
    },
    "FACILITY- CONSULTATION/TREATMENT ROOM": {
        "showOnly": [
            "Does the consultation room have adequate space?",
            "Does the consultation room have wheelchair accessibility",
            "At least 3 Chairs",
            "Alcohol swabs",
            "Appropriate hand drying facilities",
            "Appropriate soap dispenser",
            "Cabinet/Storage space",
            "clinical waste bin with lid",
            "Cotton swabs soaked in alcohol",
            "Cotton wool/ wipes",
            "Couch",
            "disposable cups",
            "Disposable gloves",
            "domestic waste bin with lid",
            "Emergency tray",
            "Glucometer* and strips",
            "Hand washing basin with running hot and cold water",
            "Hand washing soap",
            "hand drying facilities",
            "HIV testing kit",
            "Non sterile gloves",
            "Psychology Testing material (intellectual tests)",
            "Reference material",
            "Sharps container",
            "Sound proof room/ booth",
            "Sphygmomanometer*",
            "Step to ease access to couch",
            "Storage space for consumables",
            "Table",
            "Tape measure",
            "Thermometer*",
            "Tissues",
            "Ultra sound jelly",
            "Waste bin with lids for domestic waste",
            "Waste bins with lids for clinical waste",
            "Weighing scale (both adult and paediatric)*",
        ]
    },
    "TOILET FACILITIES": {
        "showOnly": [
            "Is there a minimum of two toilets available (for male and",
            "Female patients)?",
            "Are they labelled male and female?",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Are toilets wheel chair accessible?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does the Facility have a policy on waste management?",
            "Does the Facility have SOPs on waste management?",
            "Does the Facility have a waste disposal system? Specify:",
            "Domestic Waste",
            "Clinical Waste",
            "Does the Facility have a policy and procedures on safety?",
            "Is there a policy and procedure on accidental eposure to HIV?",
            "Does the Facility have fire protection equipment?",
            ".Fire etinguishers",
            ".Emergency eits",
            "Additional:",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the Facility have a written program for maintaining fire protection equipment ?",
            "Does the Facility have adequate security?",
            ".A larm system?",
            "Burglar bars?",
            "Lockable gates?",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the Facility have the following policies",
            "supplies and purchasing",
            "management of epired supplies",
            "Does the Facility have adequate supplies for services provided/",
            "Is there a stock control system?",
        ]
    },
    "TENS": {
        "showOnly": [
            "Is there a customer feedback mechanism",
            "Suggestion bo",
            "Customer surveys",
            "Is there a patient charter in both English and Setswana",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
        ]
    },

};

export default Psychology;
