/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist-final.csv
 * Generated on: 2026-01-20 07:43:22
 * Facility Type: Dental
 *
 * To regenerate this file, run: python src/config/generateFilters.py
 */

const Dental = {
    "SECTION A-ORGANISATION AND MANAGEMENT": {
        "showOnly": [
            "Does the Facility have an organisational structure",
            "Is the director a medically trained person?",
            "Does the facility have the following  requirements? --",
            "Business registration",
            "Tax clearance certificate",
            "Valid private pactice license",
            "Work permits",
            "residence permit",
            "Lease agreement",
            "Occupancy certificate",
            "Permission to operate/set up",
            "Patient charter in English & Setswana",
            "Is there an indemnity insurance?",
            "contracts for staff",
            "Police Clearance",
            "waste collection carrier licence",
            "confidentiality clause",
            "proof of change of land use",
            "Practitioners licence",
            "Fire clearance",
            "Does the Facility have policies and procedures for the following?--",
            "Patient referral",
            "Assessment of patients",
            "Management of high risk patients",
            "The confidentiality of patient information",
            "Incident reporting",
            "Induction and orientation",
            "Patient consent",
            "Linen management",
            "Equipment maintenance plan/program",
            "Testing and commissioning certificates",
            "Infection prevention and control",
            "Management of patient records",
            "Record retention times",
            "Management of information",
            "Risk management",
            "Management of supplies",
            "Patient observation",
            "Management of medication",
            "Post exposure prophylaxis",
            "Complaints procedure",
            "Disaster preparedness",
            "Waste management",
            "Others",
            "Does the Facility have the following reference materials?--",
            "Treatment protocols/ guidelines",
            "Testing and treatment techniques",
            "Copies of relevant statutory instruments",
        ]
    },
    "SERVICES PROVIDED": {
        "showOnly": [
            "What are the services provided at the Facility?--",
            "General services; Specify",
            "Specialist services; Specify",
            "Other services (Specify);",
            "Are hours of operation displayed?",
            "State hours of operation",
            "Are emergency contact numbers displayed?",
            "What is number of patients seen/ Samples received per month",
            "Any outreach services? If yes state them.",
            "Is there permission to offer the outreach services",
            "Agreement letter with a doctor where outreach services will be offered from",
            "Is there provision of emergency outreach services?",
        ]
    },
    "PERSONNEL": {
        "showOnly": [
            "What is the intended total number of staff",
            "What is the current number of staff--",
            "General Health Professionals (Specify)",
            "Specialists (Specify)",
            "Other (specify)",
            "Administrative Staff (Specify)",
            "Support staff (Specify)",
            "Are professionals registered with the relevant Councils?",
            "Signed job effectiveness description",
            "Education credentials",
            "A signed confidentiality clause",
            "Evidence of orientation and induction",
            "Signed contracts or offer letters",
            "Medical eamination certificates",
            "Evidence of continous Professional Development",
        ]
    },
    "FACILITY-ENVIRONMENT": {
        "showOnly": [
            "Does the facility have wheelchair accessibility?",
            "Is it fenced, secure and easily accessible",
            "Is there space for parking? Specify",
            "Is there parking space designated for people living with disability? Specify",
            "Do the facility have space for services provided? Specify",
            "Is there provision for handwashing?",
            "Is facility area clean and neat?",
            "Are surfaces free from dust?",
            "Is there lighting in all service areas?",
            "Is air conditioning available?",
            "Is there ventilation in all service area?",
            "Is flooring of cleanable, smooth impervious material?",
            "Are there relevant restriction signs?",
            "Is there directional signage within and outside the facility?",
            "Is there backup system for electricity?",
            "Is there backup system for water?",
            "Where there are ramps, are there safety features?",
        ]
    },
    "FACILITY-RECEPTION/WAITING AREA": {
        "showOnly": [
            "Does reception area have adequate space? Elaborate.",
            "Is the telephone/ cell phone available?",
            "Is a reception desk and chair available",
            "Is it manned at all times?",
            "Is there an organized patient registration, screening and booking system?",
            "Are there adequate patient benches / chairs in the waiting area? Elaborate.",
            "Is there a waste bin?",
            "Is there a computer/ desktop?",
            "Is there patient charter available in Setswana and English?",
            "Is there available drinking water source?",
            "Are educational materials available for clients",
        ]
    },
    "FACILITY-SCREENING ROOM": {
        "showOnly": [
            "Does the screening room have space? Elaborate.",
            "Does the screening room have wheelchair accessibility?",
            "At least 3 Chairs",
            "Sphygmomanometer",
            "Thermometer",
            "Glucometer and strips",
            "Alcohol Swabs",
            "Weighing scale (both adult and paediatric)",
            "Height measuring device",
            "Non sterile gloves",
            "Clinical waste bin with lid",
            "Domestic waste bin with lid",
            "Sharps container",
            "Hand wash facilities",
            "Appropriate hand drying facilities",
            "Appropriate hand wash soap",
        ]
    },
    "FACILITY-CONSULTATION/ TREATMENT ROOM": {
        "showOnly": [
            "Does the consultation room have adequate space?",
            "Does the consultation room have wheelchair accessibility",
            "Chairs and a table",
            "Alcohol Swabs",
            "Appropriate hand drying facilities",
            "Appropriate soap dispenser",
            "Autoclave",
            "Cabinet/Storage space",
            "Clinical waste bin with lid",
            "Cotton wool/ wipes",
            "Curette",
            "Dental chair with headrest and all attachments",
            "Dental stools",
            "Diagnostic set*",
            "disposable cups",
            "Disposable gloves",
            "Domestic waste bin with lid",
            "Eamination chair",
            "Eamination/ treatment couch covered with linen?",
            "Eamination lamp*",
            "Forceps",
            "Glucometer and strips",
            "Hand washing basin with running hot and cold water",
            "Hand washing soap",
            "hand drying facilities",
            "Height measuring device",
            "HIV testing kit",
            "Mouth gargle",
            "Needle holders",
            "Non sterile gloves",
            "Reference material",
            "Sharps container",
            "Sphygmomanometer",
            "Sterile gloves",
            "Storage space for consumables",
            "Suction apparatus",
            "Tape measure",
            "Thermometer",
            "Tongue depressors",
            "Weighing scale (both adult and paediatric)",
        ]
    },
    "TOILET FACILITIES": {
        "showOnly": [
            "Is there a minimum of two toilets available (for Male and   Female patients)?",
            "Are toilets fitted with hand wash facilities?",
            "Is there suitable soap dispenser?",
            "Is there an appropriate hand drying provision?",
            "Is there a separate toilet for staff?",
            "Is there a toilet that is designed for wheel chair users?",
            "Does the female toilet have sanitary pads disposal?",
            "Are toilets aesthetically pleasing?",
            "Is there provision for paediatric clients?",
        ]
    },
    "SAFETY AND WASTE MANAGEMENT": {
        "showOnly": [
            "Does the Facility have a policy on waste management?",
            "Does the Facility have SOPs on waste management?",
            "Does the Facility have a waste disposal system? Specify:",
            "Domestic Waste",
            "Clinical Waste",
            "Does the Facility have a policy and procedures on safety?",
            "Is there a policy and procedure on accidental eposure to HIV?",
            "Does the Facility have fire protection equipment?",
            "Fire etinguishers",
            "Emergency eits",
            "Additional:",
            "Fire alarms",
            "Smoke detectors",
            "Fire blankets",
            "Fire Hose reel",
            "Does the Facility have a written program for maintaining fire protection equipment ?",
            "Does the Facility have adequate security?",
            "A larm system?",
            "Burglar bars?",
            "Lockable gates?",
        ]
    },
    "SUPPLIES": {
        "showOnly": [
            "Does the Facility have the following policies--",
            "supplies and purchasing",
            "management of expired supplies",
            "Does the Facility have adequate supplies for services provided",
            "Is there a stock control system?",
            "Amalgam hand instruments?",
            "Amalgam capsules?",
            "Cavity lining material",
            "Wedges",
            "Retention pins",
            "Matri holders/retainers",
            "Matri bands",
            "Articulating paper",
            "Polishing kits",
            "Hand pieces and burrs",
            "Composite filling with:",
            "Composite hand instruments",
            "Curing light",
            "Composite material",
            "Cavity liners",
            "Etching system",
            "Transparent strips",
            "Polishing kits and strips",
            "Hand pieces and burrs",
            "Root canal treatment with:--",
            "Endodontic kit with files and reamers",
            "Gutta Percha points",
            "Paper points",
            "Endo ruler",
            "Canal medicaments",
            "Root canal hand instruments",
            "Scaling with:--",
            "Scaling hand instruments",
            "Ultrasonic scaler",
            "Polishing brushes and cups",
            "Disclosing tablets",
            "Polishing paste",
            "Mouth wash tablets",
            "Oral surgery pack with:",
            "Tooth etraction forceps",
            "BP knife",
            "Surgical blades",
            "Scissors",
            "Needle holders",
            "Artery forceps",
            "Root elevators",
            "Periosteal elevators",
            "Retractors (tissue, cheek",
            "Suture material",
            "General items in treatment room:",
            "Non sterile gloves",
            "Surgical masks",
            "Dental needles",
            "Dental syringes",
            "Local anaesthetic solution",
            "Gauze",
            "Disinfectant",
            "An emergency kit ?",
        ]
    },
    "CUSTOMER SATISFACTION": {
        "showOnly": [
            "Is there a customer feedback mechanism",
            "Suggestion bo",
            "Customer surveys",
            "Is there a patient charter in both English and Setswana",
            "Is there provision for consent before carrying out any procedures/assessment",
            "Is there a complaints, procedure",
        ]
    },
    "INSTRUMENT WASHING/STERILISING ROOM": {
        "showOnly": [
            "Is there a washing room with adequate space?",
            "Is the room equipped with the following--",
            "Stainless steel sink with running water",
            "Stainless Steel Waste Discarding Sink Supplied With Hot And Cold Water",
            "Is the room ventilated? Elaborate",
            "Is the room equipped with the following--",
            "Chair",
            "Microwave",
            "Autoclave",
            "Sterilising containers",
            "Sterilising solutions",
            "Pack wrappers",
            "Disinfectant",
            "Sharps container",
            "Waste bin with lid for clinical waste",
            "Waste bin with lid for domestic waste",
            "Hand wash facilities",
            "Appropriate hand drying facilities",
            "Disposable gloves",
        ]
    },
    "ULTRASOUND ROOM": {
        "showOnly": [
            "Is there evidence of facility liason with the Primary Health Care Department? (A guide the reports to be submitted available)",
            "Is there evidence of statistical reporting to the Primary Health Care Departments as per available guideline?",
        ]
    },

};

export default Dental;
