/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: checklist-final.csv
 * Generated on: 2026-01-07 17:37:00
 *
 * This file defines facility service departments based on actual sections
 * found in the CSV checklist configuration.
 * To regenerate this file, run: python src/config/generateFilters.py
 */

// All available facility service departments (sections from CSV)
export const ALL_FACILITY_DEPARTMENTS = [
  'BLEEDING ROOM',
  'EMERGENCY EQUIPMENT',
  'FACILITY-CALL CENTRE',
  'FACILITY-CONSULTATION/ TREATMENT ROOM--',
  'FACILITY-ENVIRONMENT',
  'FACILITY-PROCEDURE ROOM',
  'FACILITY-RECEPTION/WAITING AREA--',
  'FACILITY-SCREENING ROOM--',
  'HIV SCREENING',
  'IN PATIENT ADMISSION ROOMS',
  'INSTRUMENT WASHING/STERILISING ROOM',
  'LABORATORY TESTING AREAS CHEMISTRY',
  'NURSES' STATION',
  'OFFICE FOR THE MANAGER',
  'PERSONNEL',
  'PHARMACY/DISPENSARY',
  'SAFETY AND WASTE MANAGEMENT',
  'SECTION A-ORGANISATION AND MANAGEMENT',
  'SERVICES PROVIDED',
  'SLUICE ROOM',
  'SPECIMEN RECEPTION ROOM',
  'SUPPLIES',
  'TENS',
  'TOILET FACILITIES',
  'ULTRASOUND ROOM',
  'X-RAY ROOM',
];

// Mapping of specializations to their available departments
export const SPECIALIZATION_DEPARTMENT_MAPPING = {
  'Obstetrics & Gynaecology': [
    'BLEEDING ROOM',
    'EMERGENCY EQUIPMENT',
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Laboratory': [
    'BLEEDING ROOM',
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA--',
    'HIV SCREENING',
    'LABORATORY TESTING AREAS CHEMISTRY',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SPECIMEN RECEPTION ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Psychology': [
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA--',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Eye (Opthalmology /Optometry)': [
    'BLEEDING ROOM',
    'EMERGENCY EQUIPMENT',
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Physiotherapy': [
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Dental': [
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'INSTRUMENT WASHING/STERILISING ROOM',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Dental Laboratory': [
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA--',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Ear, Nose & Throat': [
    'BLEEDING ROOM',
    'EMERGENCY EQUIPMENT',
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Rehabilitation Centre': [
    'BLEEDING ROOM',
    'EMERGENCY EQUIPMENT',
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'IN PATIENT ADMISSION ROOMS',
    'NURSES' STATION',
    'OFFICE FOR THE MANAGER',
    'PERSONNEL',
    'PHARMACY/DISPENSARY',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Radiology': [
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-RECEPTION/WAITING AREA--',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
    'X-RAY ROOM',
  ],

  'General Practice': [
    'BLEEDING ROOM',
    'EMERGENCY EQUIPMENT',
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'PERSONNEL',
    'PHARMACY/DISPENSARY',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Paediatric': [
    'BLEEDING ROOM',
    'EMERGENCY EQUIPMENT',
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Nursing  Home': [
    'BLEEDING ROOM',
    'EMERGENCY EQUIPMENT',
    'FACILITY-CONSULTATION/ TREATMENT ROOM--',
    'FACILITY-ENVIRONMENT',
    'FACILITY-PROCEDURE ROOM',
    'FACILITY-RECEPTION/WAITING AREA--',
    'FACILITY-SCREENING ROOM--',
    'IN PATIENT ADMISSION ROOMS',
    'NURSES' STATION',
    'OFFICE FOR THE MANAGER',
    'PERSONNEL',
    'PHARMACY/DISPENSARY',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

  'Emergency Medical Services': [
    'FACILITY-CALL CENTRE',
    'FACILITY-ENVIRONMENT',
    'OFFICE FOR THE MANAGER',
    'PERSONNEL',
    'SAFETY AND WASTE MANAGEMENT',
    'SECTION A-ORGANISATION AND MANAGEMENT',
    'SERVICES PROVIDED',
    'SLUICE ROOM',
    'SUPPLIES',
    'TENS',
    'TOILET FACILITIES',
    'ULTRASOUND ROOM',
  ],

};

/**
 * Get departments available for a specific specialization
 * @param {string} specialization - The facility specialization
 * @returns {Array<string>} Array of department names
 */
export function getDepartmentsForSpecialization(specialization) {
  if (!specialization || !SPECIALIZATION_DEPARTMENT_MAPPING[specialization]) {
    return ALL_FACILITY_DEPARTMENTS;
  }
  return SPECIALIZATION_DEPARTMENT_MAPPING[specialization];
}

/**
 * Get statistics about departments for a specialization
 * @param {string} specialization - The facility specialization
 * @returns {Object} Statistics object with total and available counts
 */
export function getDepartmentStats(specialization) {
  const available = getDepartmentsForSpecialization(specialization);
  return {
    total: ALL_FACILITY_DEPARTMENTS.length,
    available: available.length,
    specialization: specialization
  };
}

export default {
  ALL_FACILITY_DEPARTMENTS,
  SPECIALIZATION_DEPARTMENT_MAPPING,
  getDepartmentsForSpecialization,
  getDepartmentStats
};
